(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var l="function"==typeof Object.defineProperties?Object.defineProperty:; 
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var t=ba(this),ca="function"===typeof Symbol&&"symbol"===typeof Symbol("x"),w={},da={};function y(a,b){var c=da[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]} 
function z(a,b,c){if(b)a:{var d=a.split(".");a=1===d.length;var e=d[0],f;!a&&e in w?f=w:f=t;for(e=0;e<d.length-1;e++){var g=d[e];if(!(g in f))break a;f=f[g]}d=d[d.length-1];c=ca&&"es6"===c?f[d]:null;b=b(c);null!=b&&(a?l(w,d,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===da[d]&&(a=1E9*Math.random()>>>0,da[d]=ca?t.Symbol(d):"$jscp$"+a+"$"+d),l(f,da[d],{configurable:!0,writable:!0,value:b})))}} 
z("Symbol",function(a){if(a)return a;c.prototype.toString=;var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b},"es6"); 
z("Symbol.iterator",function(a){if(a)return a;a=(0,w.Symbol)("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=t[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&l(d.prototype,a,{configurable:!0,writable:!0,value:})}return a},"es6"); 
z("String.prototype.endsWith",function(a){return a?a:},"es6");z("globalThis",function(a){return a||t},"es_2020"); 
z("Array.prototype.values",function(a){return a?a:},"es8");z("Array.prototype.keys",function(a){return a?a:},"es6"); 
z("Object.values",function(a){return a?a:},"es8");var B=this||self;function ha(a){return a};function ia(a){a=parseFloat(a);return isNaN(a)||1<a||0>a?0:a};var la={},ka={};var ma=Array.prototype.indexOf?:,na=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:;var oa;function pa(a,b){this.g=b===qa?a:""}pa.prototype.toString=;function ra(a){return a instanceof pa&&a.constructor===pa?a.g:"type_error:TrustedResourceUrl"}var sa=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,qa={}; 
function ta(a){if(void 0===oa){var b=null;var c=B.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:ha,createScript:ha,createScriptURL:ha})}catch(d){B.console&&B.console.error(d.message)}oa=b}else oa=b}a=(b=oa)?b.createScriptURL(a):a;return new pa(a,qa)} 
;function xa(a){var b;a:{if(b=B.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};/* 
 
 SPDX-License-Identifier: Apache-2.0 
*/ 
function ya(a,b){a.src=ra(b);var c,d;(c=(b=null==(d=(c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:d.call(c,"script[nonce]"))?b.nonce||b.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};function za(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};Aa[" "]=;function Ba(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};var Ca=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Ea(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1}var Fa=/#|$/; 
function D(a,b){var c=a.search(Fa),d=Ea(a,0,b,c);if(0>d)return null;var e=a.indexOf("&",d);if(0>e||e>c)e=c;d+=b.length+1;return decodeURIComponent(a.slice(d,-1!==e?e:0).replace(/\+/g," "))}var Ga=/[?&]($|#)/; 
function E(a,b,c){for(var d=a.search(Fa),e=0,f,g=[];0<=(f=Ea(a,e,b,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.slice(e));a=g.join("").replace(Ga,"$1");c=null!=c?"="+encodeURIComponent(String(c)):"";(b+=c)?(c=a.indexOf("#"),0>c&&(c=a.length),d=a.indexOf("?"),0>d||d>c?(d=c,e=""):e=a.substring(d+1,c),c=[a.slice(0,d),e,a.slice(c)],a=c[1],c[1]=b?a?a+"&"+b:b:a,b=c[0]+(c[1]?"?"+c[1]:"")+c[2]):b=a;return b};function Ha(){if(!w.globalThis.crypto)return Math.random();try{var a=new Uint32Array(1);w.globalThis.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}}function Ia(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)}var Ka=za(function(){return na(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],Ja)||1E-4>Math.random()}),La=za(function(){return xa("MSIE")});function Ja(a){return xa(a)} 
function F(a){return/^true$/.test(a)};var Na=ia("0.20"),Oa=ia("0.002"),Pa=ia("0.00"),Qa=ia("0.00"),Ra=F("true"),Sa=F("true"),Ta=F("true"),Ua=F("true");var Va=null;function Wa(){if(null===Va){Va="";try{var a="";try{a=B.top.location.hash}catch(c){a=B.location.hash}if(a){var b=a.match(/\bdeid=([\d,]+)/);Va=b?b[1]:""}}catch(c){}}return Va} 
function Xa(a,b,c){var d=G;if(c?d.g.hasOwnProperty(c)&&""==d.g[c]:1){var e;e=(e=Wa())?(e=e.match(new RegExp("\\b("+a.join("|")+")\\b")))?e[0]:null:null;if(e)a=e;else a:{if(!La()&&!Ka()&&(e=Math.random(),e<b)){e=Ha();a=a[Math.floor(e*a.length)];break a}a=null}a&&""!=a&&(c?d.g.hasOwnProperty(c)&&(d.g[c]=a):d.i[a]=!0)}}function Ya(a){var b=G;return b.g.hasOwnProperty(a)?b.g[a]:""}function Za(){var a=G,b=[];Ia(a.i,);Ia(a.g,function(c){""!=c&&b.push(c)});return b};var $a={K:2,S:13,R:14,N:16,M:17,L:18,J:19},G=null;function ab(){return!!G&&"592230571"==Ya(16)};function bb(a){return"function"===typeof a}var cb=Array.isArray;;var gb=new function(a,b){this.g=a;this.defaultValue=void 0===b?!1:b}(1933);var I=window,K=document,hb={onload:1,src:1,width:1,height:1,style:1};;var kb={};;function M(a){var b="u";if(a.u&&a.hasOwnProperty(b))return a.u;b=new a;return a.u=b};function lb(){var a={};this.g=;this.i=function(b){a[gb.g]=b}};var N=[]; 
 
 
; 
var Hb=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Ib=/(^|\.)doubleclick\.net$/i; 
 
;; 
;var Lb=/:[0-9]+$/; 
;var Pb={};var Qb=/^\w+$/,Rb=/^[\w-]+$/,Sb={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp",gb:"_gb"}; 
 
 
 
 
 
 
 
;var kc=RegExp("^UA-\\d+-\\d+%3A[\\w-]+(?:%2C[\\w-]+)*(?:%3BUA-\\d+-\\d+%3A[\\w-]+(?:%2C[\\w-]+)*)*$"),lc=/^~?[\w-]+(?:\.~?[\w-]+)*$/,mc=/^\d+\.fls\.doubleclick\.net$/,nc=/;gac=([^;?]+)/,oc=/;gacgb=([^;?]+)/,pc=/;gclaw=([^;?]+)/,qc=/;gclgb=([^;?]+)/; 
 
 
;;var Ac={O:0,G:1,P:2,I:3,H:4}; 
;function Hc(a,b,c){a=Ic(a,!0);if(a[b])return!1;a[b]=[];a[b][0]=c;return!0}function Ic(a,b){var c=a.GooglebQhCsO;c||(c={},b&&(a.GooglebQhCsO=c));return c};var Jc={},Kc=null; 
function Lc(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}a=4;void 0===a&&(a=0);if(!Kc)for(Kc={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));Jc[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===Kc[h]&&(Kc[h]=g)}}a=Jc[a];c=Array(Math.floor(b.length/3));d=a[64]||"";for(e=f=0;f<b.length-2;f+=3){var k=b[f],m=b[f+1];h=b[f+2];g=a[k>>2];k=a[(k& 
3)<<4|m>>4];m=a[(m&15)<<2|h>>6];h=a[h&63];c[e++]=g+k+m+h}g=0;h=d;switch(b.length-f){case 2:g=b[f+1],h=a[(g&15)<<2]||d;case 1:b=b[f],c[e]=a[b>>2]+a[(b&3)<<4|g>>4]+h+d}return c.join("")};function Mc(a,b,c,d){var e=D(c,"fmt");if(d){var f=D(c,"random"),g=D(c,"label")||"";if(!f)return!1;f=Lc(decodeURIComponent(g.replace(/\+/g," "))+":"+decodeURIComponent(f.replace(/\+/g," ")));if(!Hc(a,f,d))return!1}e&&4!=e&&(c=E(c,"rfmt",e));c=E(c,"fmt",4);e=Ba("SCRIPT");ya(e,ta(c));e.onload=function(){a.google_noFurtherRedirects&&d&&d.call&&(a.google_noFurtherRedirects=null,d())};b.getElementsByTagName("script")[0].parentElement.appendChild(e);return!0};var Nc=F("false");function Oc(){if(bb(I.__uspapi)){var a="";try{I.__uspapi("getUSPData",1,)}catch(b){}return a}};var Pc={id:!0,origin:!0,destination:!0,start_date:!0,end_date:!0,location_id:!0},Qc=/^[a-zA-Z0-9_]+$/,Rc=!1,Sc="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_currency google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_enable_display_cookie_match google_gtag_event_data google_remarketing_only google_conversion_linker google_tag_for_child_directed_treatment google_tag_for_under_age_of_consent google_allow_ad_personalization_signals google_restricted_data_processing google_conversion_items google_conversion_merchant_id google_user_id google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_gtm_url_processor google_conversion_page_url google_conversion_referrer_url google_gtm google_gcl_cookie_prefix google_gcl_cookie_path google_gcl_cookie_flags google_gcl_cookie_domain google_gcl_cookie_max_age_seconds google_read_gcl_cookie_opt_out google_basket_feed_country google_basket_feed_language google_basket_discount google_basket_transaction_type google_additional_conversion_params google_additional_params google_transport_url google_gtm_experiments".split(" "); 
function S(a){return null!=a?encodeURIComponent(String(a)):""}function Uc(a){if(null!=a){a=String(a).substring(0,512);var b=a.indexOf("#");return-1==b?a:a.substring(0,b)}return""}function T(a,b){b=S(b);return""!=b&&(a=S(a),""!=a)?"&".concat(a,"=",b):""}function Vc(a){var b=typeof a;return null==a||"object"==b||"function"==b?null:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")} 
function Wc(a){if(!a||"object"!=typeof a||"function"==typeof a.join)return"";var b=[],c;for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)){var d=a[c];if(d&&"function"===typeof d.join){for(var e=[],f=0;f<d.length;++f){var g=Vc(d[f]);null!=g&&e.push(g)}d=0==e.length?null:e.join(",")}else d=Vc(d);(e=Vc(c))&&null!=d&&b.push(e+"="+d)}return b.join(";")} 
function Xc(a,b){if(b.google_read_gcl_cookie_opt_out||b.google_remarketing_only||b.google_conversion_domain&&(!b.google_gcl_cookie_prefix||!/^_ycl/.test(b.google_gcl_cookie_prefix)))return"";var c="",d=Yc(b),e={};b.google_gcl_cookie_domain&&(e.domain=b.google_gcl_cookie_domain);b.google_gcl_cookie_flags&&(e.flags=b.google_gcl_cookie_flags);null!=b.google_gcl_cookie_max_age_seconds&&(e.A=b.google_gcl_cookie_max_age_seconds);b.google_gcl_cookie_path&&(e.path=b.google_gcl_cookie_path);d&&(e.prefix=d); 
if(Zc(b)&&b.l)var f=void 0===b.m;else mc.test(a.location.host)?f=!(pc.test(a.location.href)||nc.test(a.location.href)):(f=Math.max(ic("aw",d),jc(Q()?P():{})),f=Math.max(ic("gb",d),jc(Q()?P("_gac_gb",!0):{}))>f);if(f){if(void 0!==b.m)return b.m;c=vc(a,d||void 0);f=b.google_conversion_label;var g=yc(f,e,b.l);c=T("gclgb",c)+(g?T("mcov",g):"");if(d)return b.m=c;d=sc(a,f,e,b.l);a=d.D;d=d.F;c+=(a?T("gacgb",a):"")+(d?T("gacmcov",d):"");return b.m=c}if(d)return b=uc(a,d),T("gclaw",b);(b=uc(a))&&(c=T("gclaw", 
b));b=rc(a,Q()?P():{},nc);return c+(b?T("gac",b):"")}function $c(a){function b(d){try{return decodeURIComponent(d),!0}catch(e){return!1}}a=a?a.title:"";if(void 0==a||""==a)return"";a=encodeURIComponent(a);for(var c=256;!b(a.substr(0,c));)c--;return"&tiba="+a.substr(0,c)} 
function ad(a,b,c,d,e,f){var g="https://",h="landing"===d.google_conversion_type?"/extclk":"/";switch(e){default:return"";case 2:case 3:var k="googleads.g.doubleclick.net/";var m="pagead/viewthroughconversion/";break;case 1:k="www.google.com/";m="pagead/1p-conversion/";break;case 6:k="www.google.com/";m="ccm/conversion/";break;case 0:k=d.google_conversion_domain||"www.googleadservices.com/";m="pagead/conversion/";break;case 5:k=d.google_conversion_domain||"www.googleadservices.com/";m="ccm/conversion/"; 
break;case 4:k=(k=d.google_gtm_experiments)&&k.apcm?"www.google.com":k&&k.capiorig?d.google_conversion_id+".privacysandbox.googleadservices.com":"www.google.com/";m="pagead/privacysandbox/conversion/";break;case 7:k="googleads.g.doubleclick.net/",m="td/rul/"}Ra&&d.google_transport_url&&(k=d.google_transport_url);"/"!==k[k.length-1]&&(k+="/");if(0===k.indexOf("http://")||0===k.indexOf("https://"))g="";g=[g,k,m,S(d.google_conversion_id),h,"?random=",S(d.google_conversion_time)].join("");h=T("cv",d.google_conversion_js_version); 
k=T("fst",d.google_conversion_first_time);m=T("num",d.google_conversion_snippets);var n=T("fmt",d.google_conversion_format),p=d.google_remarketing_only?T("userId",d.google_user_id):"";var q=d.google_tag_for_child_directed_treatment;q=null==q||0!==q&&1!==q?"":T("tfcd",q);var u=d.google_tag_for_under_age_of_consent;u=null==u||0!==u&&1!==u?"":T("tfua",u);var C=d.google_allow_ad_personalization_signals;C=!1===C?T("npa",1):!0===C?T("npa",0):"";var V=d.google_restricted_data_processing;V=Ta?!0===V?T("rdp", 
1):!1===V?T("rdp",0):"":"";var kd=T("value",d.google_conversion_value),ld=T("currency_code",d.google_conversion_currency),md=T("label",d.google_conversion_label),nd=T("oid",d.google_conversion_order_id),od=T("bg",d.google_conversion_color);a:{var x=d.google_conversion_language;if(null!=x){x=x.toString();if(2==x.length){x=T("hl",x);break a}if(5==x.length){x=T("hl",x.substring(0,2))+T("gl",x.substring(3,5));break a}}x=""}var pd=T("guid","ON"),qd=!d.google_conversion_domain&&"GooglemKTybQhCsO"in B&& 
"function"==typeof B.GooglemKTybQhCsO?T("resp","GooglemKTybQhCsO"):"",rd=T("disvt",d.google_disable_viewthrough),sd=T("eid",Za().join());var W=d.google_conversion_date;var v=[];if(a){var H=a.screen;H&&(v.push(T("u_h",H.height)),v.push(T("u_w",H.width)),v.push(T("u_ah",H.availHeight)),v.push(T("u_aw",H.availWidth)),v.push(T("u_cd",H.colorDepth)));a.history&&v.push(T("u_his",a.history.length))}W&&"function"==typeof W.getTimezoneOffset&&v.push(T("u_tz",-W.getTimezoneOffset()));b&&("function"==typeof b.javaEnabled&& 
v.push(T("u_java",b.javaEnabled())),b.plugins&&v.push(T("u_nplug",b.plugins.length)),b.mimeTypes&&v.push(T("u_nmime",b.mimeTypes.length)));W=v.join("");v=T("gtm",d.google_gtm);b=b&&b.sendBeacon?T("sendb","1"):"";H=bd();var ud=T("ig",/googleadservices\.com/.test("www.googleadservices.com")?1:0),ua=Wc(d.google_custom_params);f=Wc(f);f=ua.concat(0<ua.length&&0<f.length?";":"",f);f=""==f?"":"&".concat("data=",encodeURIComponent(f));ua=Xc(c,d);var Ub=d.google_conversion_page_url,vd=d.google_conversion_referrer_url, 
va="";if(c){if(a.top==a)var r=0;else{var J=a.location.ancestorOrigins;if(J)r=J[J.length-1]==a.location.origin?1:2;else{J=a.top;try{var A;if(A=!!J&&null!=J.location.href)c:{try{Aa(J.foo);A=!0;break c}catch(wd){}A=!1}r=A}catch(wd){r=!1}r=r?1:2}}A=Ub?Ub:1==r?a.top.location.href:a.location.href;va+=T("frm",r);va+=T("url",Uc(A));va+=T("ref",Uc(vd||c.referrer))}a=[h,k,m,n,p,q,u,C,V,kd,ld,md,nd,od,x,pd,qd,rd,sd,W,v,b,H,ud,f,ua,va,$c(c),cd(d.google_additional_params),cd(d.google_remarketing_only?{}:d.google_additional_conversion_params), 
"&hn="+S("www.googleadservices.com"),dd(a)].join("");c=Wa();a+=0<c.length?"&debug_experiment_id="+c:"";if(!d.google_remarketing_only&&!d.google_conversion_domain){c=[T("mid",d.google_conversion_merchant_id),T("fcntr",d.google_basket_feed_country),T("flng",d.google_basket_feed_language),T("dscnt",d.google_basket_discount),T("bttype",d.google_basket_transaction_type)].join("");if(d)if(r=d.google_conversion_items){A=[];h=0;for(k=r.length;h<k;h++)m=r[h],n=[],m&&(n.push(U(m.value)),n.push(U(m.quantity)),n.push(U(m.item_id)), 
n.push(U(m.start_date)),n.push(U(m.end_date)),A.push("("+n.join("*")+")"));r=0<A.length?"&item="+A.join(""):""}else r="";else r="";c=[a,c,r].join("");a=4E3<c.length?[a,T("item","elngth")].join(""):c}g+=a;1===e||6===e?g+=[T("gcp",1),T("sscte",1),T("ct_cookie_present",1)].join(""):3==e&&(g+=T("gcp",1),g+=T("ct_cookie_present",1));Sa&&(e=Oc(),void 0!==e&&(g+=T("us_privacy",e||"error")));Zc(d)&&(g=d.l?g+T("gbcov",1):g+T("gbcov",0));return g} 
function gd(a,b,c,d,e,f){var g=c.onload_callback,h;e&&g&&g.call?h=g:h=;d+=T("async","1");e=c.google_gtm_url_processor;bb(e)&&(d=e(d));g=(e=c.opt_image_generator)&&e.call;if(!(f=g||!f)){if(c.google_conversion_domain)var k=!1;else try{k=Mc(a,b,d,h)}catch(m){k=!1}f=!k}f&&(a=fd,g&&(a=e),a=a(),a.src=d,a.onload=h)} 
function hd(a,b){G&&"376635471"==Ya(2)&&("complete"===b.readyState?ed(b):a.addEventListener?a.addEventListener("load",):a.attachEvent("onload",))} 
function id(a){if("landing"===a.google_conversion_type||!a.google_conversion_id||a.google_remarketing_only&&a.google_disable_viewthrough)return!1;a.google_conversion_date=new Date;a.google_conversion_time=a.google_conversion_date.getTime();a.google_conversion_snippets="number"===typeof a.google_conversion_snippets&&0<a.google_conversion_snippets?a.google_conversion_snippets+1:1;void 0===a.google_conversion_first_time&&(a.google_conversion_first_time=a.google_conversion_time);a.google_conversion_js_version= 
"9";0!=a.google_conversion_format&&1!=a.google_conversion_format&&2!=a.google_conversion_format&&3!=a.google_conversion_format&&(a.google_conversion_format=3);!1!==a.google_enable_display_cookie_match&&(a.google_enable_display_cookie_match=!0);return!0}function jd(a,b){function c(f){d[f]=b&&null!=b[f]?b[f]:a[f]}for(var d={},e=0;e<Sc.length;e++)c(Sc[e]);c("onload_callback");return d} 
 
function bd(){var a="";ab()&&(a=Gc().map().join("_"));return T("li",a)}function dd(a){if(!Ua||!a.__gsaExp||!a.__gsaExp.id)return"";a=a.__gsaExp.id;if(!bb(a))return"";try{var b=Number(a());return isNaN(b)?"":T("gsaexp",b)}catch(c){return""}}function cd(a){if(!a)return"";var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+=T(c,a[c]));return b}function Zc(a){return(a=a.google_gtm_experiments)&&a.gbcov?!0:!1} 
 
 
;var Ad=!1,Bd=document.currentScript&&document.currentScript.src||""; 
function Cd(a,b,c){try{if(!Ad&&(Ad=!0,!c.google_gtm)){var d=void 0,e=D(a.location.href,"gtm_debug");Dd(e)&&(d=2);d||0!==b.referrer.indexOf("https://tagassistant.google.com/")||(d=3);var f;if(f=!d)f=0<=ma(b.cookie.split("; "),"__TAG_ASSISTANT=x");f&&(d=4);if(!d){var g=b.documentElement.getAttribute("data-tag-assistant-present");Dd(g)&&(d=5)}if(d){var h="AW-"+(c.google_conversion_id||"");if(!a["google.tagmanager.debugui2.queue"]){a["google.tagmanager.debugui2.queue"]=[];var k=new ja(ka,"https://www.googletagmanager.com/debug/bootstrap"); 
var m=ta(k instanceof ja&&k.constructor===ja&&k.g===la?k.i:"type_error:Const");c={id:h,src:"LEGACY",cond:d};var n=sa.exec(ra(m).toString()),p=n[3]||"";var q=ta(n[1]+wa("?",n[2]||"",c)+wa("#",p));var u=Ma("SCRIPT",b);ya(u,q);var C=b.getElementsByTagName("script")[0];C&&C.parentNode&&C.parentNode.insertBefore(u,C)}a["google.tagmanager.debugui2.queue"].push({messageType:"LEGACY_CONTAINER_STARTING",data:{id:h,scriptSource:Bd}})}}}catch(V){}} 
; 
function Fd(a,b,c,d){Cd(a,c,d);ab()&&(Dc(2),d.google_gtm&&Fc(M(Bc),a));var e=!1;if(3!=d.google_conversion_format)return!1;try{if(id(d)){d.google_remarketing_only&&d.google_enable_display_cookie_match&&!Nc&&G&&Xa(["376635470","376635471"],Na,2);d.google_remarketing_only&&!d.google_conversion_domain&&G&&Xa(["759238990","759238991"],Qa,13);!d.google_remarketing_only||d.google_conversion_domain||G&&("759248991"==Ya(14)||"759248990"==Ya(14))||G&&Xa(["759248990","759248991"],Pa,14);!1!==d.google_conversion_linker&& 
(d.google_gtm||xc(d.google_gcl_cookie_prefix));if(1==d.google_remarketing_only&&null!=d.google_gtag_event_data&&null!=d.google_gtag_event_data.items&&d.google_gtag_event_data.items.constructor===Array&&0<d.google_gtag_event_data.items.length)Gd(a,b,c,d);else{var f=d.google_gtm_experiments&&d.google_gtm_experiments.ccmpp;if(d.google_conversion_domain||d.google_transport_url&&"https://pagead2.googlesyndication.com/"!==d.google_transport_url)f=!1;var g=!1;y("www.googleadservices.com","endsWith").call("www.googleadservices.com", 
"google.com")&&(g=!0);var h=d.google_additional_params;h&&h.dg&&(g="e"===h.dg);h=function(k,m,n){m=void 0===m?!0:m;n=void 0===n?!0:n;gd(a,c,d,ad(a,b,c,d,k),m,n)};d.google_gtm_experiments&&d.google_gtm_experiments.fledge&&(d.google_additional_params=d.google_additional_params||{},d.google_additional_params.fledge="1");d.google_remarketing_only?h(2):g?(Ed(d,f?3:2),xd(c,d),h(1),h(3),f&&h(6,!0,!1)):(Ed(d,f?2:1),xd(c,d),h(0),f&&h(5,!0,!1),Zc(d)&&wc(c,Yc(d))&&(d.l=!0,h(0,!1)));d.google_gtm_experiments&& 
d.google_gtm_experiments.fledge&&zd(a,b,c,d)}d.google_remarketing_only&&d.google_enable_display_cookie_match&&hd(a,c);e=!0}}catch(k){}return e} 
;G=new function(){var a=[],b=0,c;for(c in $a)a[b++]=$a[c];this.i={};this.g={};a=a||[];b=0;for(c=a.length;b<c;++b)this.g[a[b]]=""};Xa(["592230570","592230571"],Oa,16);ab()&&(Dc(1),Ec()); 
var X=["GooglemKTybQhCsO"],Y=B;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Hd?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Hd; 
window.google_trackConversion=function(a){var b=window,c=navigator,d=document;a=jd(b,a);a.google_conversion_format=3;var e=!!a.google_gtm;M(lb).i(e);return Fd(b,c,d,a)};}).call(this);
