(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n,aa=,ba="function"==typeof Object.defineProperties?Object.defineProperty:,ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");},p=ca(this),
r=function(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
r("Symbol",function(a){if(a)return a;var b=;b.prototype.toString=;var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=;return e});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:})}return a});r("Symbol.asyncIterator",function(a){return a?a:Symbol("Symbol.asyncIterator")});
var da=,u=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},w=function(a){if(!(a instanceof Array)){a=u(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},ea=,fa="function"==typeof Object.assign?Object.assign:;r("Object.assign",function(a){return a||fa});var ha="function"==typeof Object.create?Object.create:,ia;if("function"==typeof Object.setPrototypeOf)ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},na={};try{na.__proto__=ka;ja=na.a;break a}catch(a){}ja=!1}ia=ja?:null}
var oa=ia,y=function(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(oa)oa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.mf=b.prototype},pa=,qa=;pa.prototype.jb=;
pa.prototype.qb=;pa.prototype.return=;var ra=;ra.prototype.jb=;var ua=;
ra.prototype.qb=;
var sa=,ta=,va=,wa=,xa=,z=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};
r("Promise",function(a){if(a)return a;b.prototype.Tc=;var d=p.setTimeout;b.prototype.Uc=;b.prototype.le=;b.prototype.Vd=;var e=;e.prototype.fc=;e.prototype.bf=;
e.prototype.af=;e.prototype.Dc=;e.prototype.cd=;e.prototype.zd=;e.prototype.cf=;e.prototype.Qe=;e.prototype.me=;var f=new b;e.prototype.df=;e.prototype.ef=;e.prototype.then=;e.prototype.catch=;e.prototype.wb=;e.resolve=c;e.reject=;e.race=;e.all=;return e});
r("WeakMap",function(a){if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(t){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,h=;h.prototype.set=;h.prototype.get=;h.prototype.has=;h.prototype.delete=;return h});
r("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(u([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||"t"!=m.value[1]||!l.next().done?!1:!0}catch(t){return!1}}())return a;var b=new WeakMap,c=;c.prototype.set=;c.prototype.delete=;c.prototype.clear=;c.prototype.has=;c.prototype.get=;c.prototype.entries=;c.prototype.keys=;c.prototype.values=;c.prototype.forEach=;c.prototype[Symbol.iterator]=c.prototype.entries;var d=,e=,f=,g=0;return c});var ya=;r("Array.prototype.keys",function(a){return a?a:});
r("Array.prototype.values",function(a){return a?a:});r("Object.values",function(a){return a?a:});r("Array.prototype.entries",function(a){return a?a:});
r("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(u([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;var b=;b.prototype.add=;b.prototype.delete=;b.prototype.clear=;b.prototype.has=;b.prototype.entries=;b.prototype.values=;b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=;return b});r("Array.prototype.fill",function(a){return a?a:});var za=function(a){return a?a:Array.prototype.fill};r("Int8Array.prototype.fill",za);r("Uint8Array.prototype.fill",za);
r("Uint8ClampedArray.prototype.fill",za);r("Int16Array.prototype.fill",za);r("Uint16Array.prototype.fill",za);r("Int32Array.prototype.fill",za);r("Uint32Array.prototype.fill",za);r("Float32Array.prototype.fill",za);r("Float64Array.prototype.fill",za);r("Object.entries",function(a){return a?a:});r("Object.is",function(a){return a?a:});
r("Array.prototype.includes",function(a){return a?a:});r("String.prototype.includes",function(a){return a?a:});
var Aa=this||self,Ba=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},Ca=function(a){var b=Ba(a);return"array"==b||"object"==b&&"number"==typeof a.length},Da=,Ea=function(a,b){function c(){}c.prototype=b.prototype;a.mf=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Jf=};var Fa=function(){this.Gd=0};Fa.prototype.ja=function(a,b){var c=this;return function(){var d=z.apply(0,arguments);c.Gd=a;return b.apply(null,w(d))}};var Ga=function(){this.M=[];this.P=[];this.eb=!1},Ha=function(a,b){a.M.push(b);1===a.M.length&&a.flush()},Ja=function(a,b){a.P.push(b);0===a.M.length&&1===a.P.length&&a.flush()};
Ga.prototype.flush=function(){if(!this.eb){for(this.eb=!0;0<this.M.length||0<this.P.length;){try{for(;0<this.M.length;)this.M[0](),this.M.shift()}catch(b){throw this.P.splice(0,this.P.length),this.M.splice(0,this.M.length),this.eb=!1,b;}try{var a=this.P.slice();for(this.P.splice(0,this.P.length);0<a.length;)a[0](),a.shift()}catch(b){throw this.P.splice(0,this.P.length),this.M.splice(0,this.M.length),this.eb=!1,b;}}this.eb=!1}};
p.Object.defineProperties(Ga.prototype,{xd:{configurable:!0,enumerable:!0,get:function(){return 0<this.M.length||0<this.P.length}}});Ea(Ka,Error);Ka.prototype.name="CustomError";var La;Ea(Ma,Ka);Ma.prototype.name="AssertionError";
var A=function(a,b,c){a||Na("",null,b,Array.prototype.slice.call(arguments,2));return a},Oa=function(a,b,c){null==a&&Na("Expected to exist: %s.",[a],b,Array.prototype.slice.call(arguments,2));return a},Pa=,Qa=,Ra=function(a,b,c){"string"!==typeof a&&Na("Expected string but got %s: %s.",
[Ba(a),a],b,Array.prototype.slice.call(arguments,2))},Sa=function(a,b,c){"function"!==typeof a&&Na("Expected function but got %s: %s.",[Ba(a),a],b,Array.prototype.slice.call(arguments,2))},Ta=,Ua=function(a,b,c){Array.isArray(a)||Na("Expected array but got %s: %s.",[Ba(a),a],b,Array.prototype.slice.call(arguments,2))},Va=,Xa=function(a,b,c,d){a instanceof b||Na("Expected instanceof %s but got %s.",[Wa(b),Wa(a)],c,Array.prototype.slice.call(arguments,3));return a};;var Ya=Array.prototype.forEach?:,Za=Array.prototype.map?function(a,b){A(null!=a.length);return Array.prototype.map.call(a,b,void 0)}:;
function ab(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function bb(a,b,c){if(!Ca(a)||!Ca(b)||a.length!=b.length)return!1;var d=a.length;c=c||cb;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return!1;return!0}function cb(a,b){return a===b};var fb=String.prototype.trim?:,gb=;function hb(){var a=Aa.navigator;return a&&(a=a.userAgent)?a:""}function C(a){return-1!=hb().indexOf(a)};function ib(){return C("Safari")&&!(jb()||C("Coast")||C("Opera")||C("Edge")||C("Edg/")||C("OPR")||C("Firefox")||C("FxiOS")||C("Silk")||C("Android"))}function jb(){return(C("Chrome")||C("CriOS"))&&!C("Edge")||C("Silk")}function kb(){return C("Android")&&!(jb()||C("Firefox")||C("FxiOS")||C("Opera")||C("Silk"))};var lb=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36)};/*


 Copyright (c) 2015-2018 Google, Inc., Netflix, Inc., Microsoft Corp. and contributors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var mb=!1,nb={,get U(){return mb}};var ob="function"===typeof Symbol&&Symbol.observable||"@@observable";;var qb={closed:!0,next:,error:,complete:};var rb=function(){a.prototype=Object.create(Error.prototype);return a}();var sb=Array.isArray||;function tb(a){return"function"===typeof a};function ub(a){return null!==a&&"object"===typeof a};var D=function(a){this.closed=!1;this.Ha=this.na=null;a&&(this.Kd=!0,this.ca=a)};
D.prototype.unsubscribe=function(){if(!this.closed){var a=this.na,b=this.Kd,c=this.ca,d=this.Ha;this.closed=!0;this.Ha=this.na=null;if(a instanceof D)a.remove(this);else if(null!==a)for(var e=0;e<a.length;++e)a[e].remove(this);if(tb(c)){b&&(this.ca=void 0);try{c.call(this)}catch(k){var f=k instanceof rb?vb(k.errors):[k]}}if(sb(d)){e=-1;for(var g=d.length;++e<g;){var h=d[e];if(ub(h))try{h.unsubscribe()}catch(k){f=f||[],k instanceof rb?f=f.concat(vb(k.errors)):f.push(k)}}}if(f)throw new rb(f);}};
D.prototype.add=function(a){var b=a;if(!a)return D.EMPTY;switch(typeof a){case "function":b=new D(a);case "object":if(b===this||b.closed||"function"!==typeof b.unsubscribe)return b;if(this.closed)return b.unsubscribe(),b;b instanceof D||(a=b,b=new D,b.Ha=[a]);break;default:throw Error("o`"+a);}var c=b.na;if(null===c)b.na=this;else if(c instanceof D){if(c===this)return b;b.na=[c,this]}else if(-1===c.indexOf(this))c.push(this);else return b;a=this.Ha;null===a?this.Ha=[b]:a.push(b);return b};
D.prototype.remove=function(a){var b=this.Ha;b&&(a=b.indexOf(a),-1!==a&&b.splice(a,1))};var wb=new D;wb.closed=!0;D.EMPTY=wb;;var E=function(a,b,c){D.call(this);this.Nb=null;this.o=this.L=this.Mb=!1;switch(arguments.length){case 0:this.destination=qb;break;case 1:if(!a){this.destination=qb;break}if("object"===typeof a){a instanceof E?(this.L=a.L,this.destination=a,a.add(this)):(this.L=!0,this.destination=new zb(this,a));break}default:this.L=!0,this.destination=new zb(this,a,b,c)}};y(E,D);E.EMPTY=D.EMPTY;E.create=;n=E.prototype;n.next=function(a){this.o||this.l(a)};
n.error=;n.complete=function(){this.o||(this.o=!0,this.u())};n.unsubscribe=function(){this.closed||(this.o=!0,D.prototype.unsubscribe.call(this))};n.l=function(a){this.destination.next(a)};n.H=;n.u=function(){this.destination.complete();this.unsubscribe()};n.Nd=;
var zb=function(a,b,c,d){E.call(this);this.Ua=a;var e=this;if(tb(b))var f=b;else b&&(f=b.next,c=b.error,d=b.complete,b!==qb&&(e=Object.create(b),yb(b)&&b.add(this.unsubscribe.bind(this)),e.unsubscribe=this.unsubscribe.bind(this)));this.ba=e;this.l=f;this.H=c;this.u=d};y(zb,E);zb.EMPTY=E.EMPTY;zb.create=E.create;n=zb.prototype;n.next=function(a){if(!this.o&&this.l){var b=this.Ua;nb.U&&b.L?this.Qb(b,this.l,a)&&this.unsubscribe():this.Rb(this.l,a)}};
n.error=;n.complete=function(){var a=this;if(!this.o){var b=this.Ua;if(this.u){var c=function(){return a.u.call(a.ba)};nb.U&&b.L?this.Qb(b,c):this.Rb(c)}this.unsubscribe()}};n.Rb=function(a,b){try{a.call(this.ba,b)}catch(c){this.unsubscribe();if(nb.U)throw c;pb(c)}};
n.Qb=;n.ca=function(){var a=this.Ua;this.Ua=this.ba=null;a.unsubscribe()};function Ab(a){return a};function G(){return Bb(z.apply(0,arguments))}function Bb(a){return 0===a.length?Ab:1===a.length?a[0]:function(b){return a.reduce(function(c,d){return d(c)},b)}};function Cb(a){return a&&"function"===typeof a.next&&"function"===typeof a.error&&"function"===typeof a.complete}var Db=;y(Db,E);Db.EMPTY=E.EMPTY;Db.create=E.create;var I=function(a){a&&(this.J=a)};n=I.prototype;n.hb=function(a){var b=new I;b.source=this;b.operator=a;return b};n.subscribe=function(a,b,c){var d=this.operator;a:{if(a){if(a instanceof E||Cb(a)&&yb(a))break a;if(Cb(a)){a=new Db(a);break a}}a=a||b||c?new E(a,b,c):new E(qb)}d?a.add(d.call(a,this.source)):a.add(this.source||nb.U&&!a.L?this.J(a):this.Wb(a));if(nb.U&&a.L&&(a.L=!1,a.Mb))throw a.Nb;return a};
n.Wb=function(a){try{return this.J(a)}catch(e){nb.U&&(a.Mb=!0,a.Nb=e);var b;a:{for(b=a;b;){var c=b.destination,d=b.o;if(b.closed||d){b=!1;break a}b=c&&c instanceof E?c:null}b=!0}b?a.error(e):console.warn(e)}};n.forEach=;n.J=;I.prototype[ob]=;
I.prototype.g=function(){var a=z.apply(0,arguments);return 0===a.length?this:Bb(a)(this)};I.create=;;var Fb=function(a,b){D.call(this);this.Bd=a;this.Gc=b;this.closed=!1};y(Fb,D);Fb.EMPTY=D.EMPTY;Fb.prototype.unsubscribe=function(){if(!this.closed){this.closed=!0;var a=this.Bd,b=a.ha;this.Bd=null;!b||0===b.length||a.o||a.closed||(a=b.indexOf(this.Gc),-1!==a&&b.splice(a,1))}};var Gb=function(){a.prototype=Object.create(Error.prototype);return a}();var J=function(){this.ha=[];this.ab=this.o=this.closed=!1;this.Ob=null};y(J,I);n=J.prototype;n.hb=function(a){var b=new Hb(this,this);b.operator=a;return b};n.next=function(a){if(this.closed)throw new Gb;if(!this.o){var b=this.ha,c=b.length;b=b.slice();for(var d=0;d<c;d++)b[d].next(a)}};n.error=;
n.complete=function(){if(this.closed)throw new Gb;this.o=!0;var a=this.ha,b=a.length;a=a.slice();for(var c=0;c<b;c++)a[c].complete();this.ha.length=0};n.unsubscribe=;n.Wb=function(a){if(this.closed)throw new Gb;return I.prototype.Wb.call(this,a)};n.J=function(a){if(this.closed)throw new Gb;if(this.ab)return a.error(this.Ob),D.EMPTY;if(this.o)return a.complete(),D.EMPTY;this.ha.push(a);return new Fb(this,a)};n.ya=;
J.create=;var Hb=function(a,b){J.call(this);this.destination=a;this.source=b};y(Hb,J);Hb.create=J.create;Hb.prototype.next=;Hb.prototype.error=;Hb.prototype.complete=;Hb.prototype.J=;var Ib=function(a){J.call(this);this.Xb=a};y(Ib,J);Ib.create=J.create;Ib.prototype.J=function(a){var b=J.prototype.J.call(this,a);b&&!b.closed&&a.next(this.Xb);return b};Ib.prototype.next=function(a){J.prototype.next.call(this,this.Xb=a)};p.Object.defineProperties(Ib.prototype,{value:{configurable:!0,enumerable:!0,get:function(){if(this.ab)throw this.Ob;if(this.closed)throw new Gb;return this.Xb}}});var Jb=new I();function Kb(a,b){return new I(function(c){var d=new D,e=0;d.add(b.m(function(){e===a.length?c.complete():(c.next(a[e++]),c.closed||d.add(this.m()))}));return d})};var Lb=function(a){return function(b){for(var c=0,d=a.length;c<d&&!b.closed;c++)b.next(a[c]);b.complete()}};function Mb(a,b){return b?Kb(a,b):new I(Lb(a))};function Nb(a){return a&&"function"===typeof a.m};function K(){var a=z.apply(0,arguments),b=a[a.length-1];return Nb(b)?(a.pop(),Kb(a,b)):Mb(a)};function Ob(a){return new I()};var Pb={now:,za:void 0};var Qb=function(a,b,c){a=void 0===a?Infinity:a;b=void 0===b?Infinity:b;c=void 0===c?Pb:c;J.call(this);this.pf=c;this.tb=[];this.Rc=!1;this.Mc=1>a?1:a;this.Qd=1>b?1:b;Infinity===b?(this.Rc=!0,this.next=this.Ne):this.next=this.Pe};y(Qb,J);Qb.create=J.create;n=Qb.prototype;n.Ne=function(a){var b=this.tb;b.push(a);b.length>this.Mc&&b.shift();J.prototype.next.call(this,a)};n.Pe=;
n.J=function(a){var b=this.Rc,c=b?this.tb:this.Sc(),d=c.length;if(this.closed)throw new Gb;if(this.o||this.ab)var e=D.EMPTY;else this.ha.push(a),e=new Fb(this,a);if(b)for(var f=0;f<d&&!a.closed;f++)a.next(c[f]);else for(f=0;f<d&&!a.closed;f++)a.next(c[f].value);this.ab?a.error(this.Ob):this.o&&a.complete();return e};n.Pc=;
n.Sc=;var Sb=function(a,b){b=void 0===b?Rb:b;this.Jd=a;this.now=b};Sb.prototype.m=function(a,b,c){b=void 0===b?0:b;return(new this.Jd(this,a)).m(c,b)};var Rb=Pb.now;var Tb=function(){a.prototype=Object.create(Error.prototype);return a}();function L(a,b){if(a&&"function"===typeof a.hb)return a.hb(b);throw new TypeError("r");};function Ub(){return function(a){return L(a,new Vb)}}var Vb=function(){};Vb.prototype.call=function(a,b){b.Va++;a=new Wb(a,b);var c=b.subscribe(a);a.closed||(a.connection=b.connect());return c};var Wb=function(a,b){E.call(this,a);this.Ka=b;this.connection=null};y(Wb,E);Wb.EMPTY=E.EMPTY;Wb.create=E.create;
Wb.prototype.ca=function(){var a=this.Ka;if(a){this.Ka=null;var b=a.Va;0>=b?this.connection=null:(a.Va=b-1,1<b?this.connection=null:(b=this.connection,a=a.Ga,this.connection=null,!a||b&&a!==b||a.unsubscribe()))}else this.connection=null};var Xb=;y(Xb,I);Xb.create=I.create;Xb.prototype.J=function(a){return this.Cb().subscribe(a)};Xb.prototype.Cb=function(){var a=this.vb;if(!a||a.o)this.vb=this.Cd();return this.vb};Xb.prototype.connect=function(){var a=this.Ga;a||(this.ub=!1,a=this.Ga=new D,a.add(this.source.subscribe(new Yb(this.Cb(),this))),a.closed&&(this.Ga=null,a=D.EMPTY));return a};Xb.prototype.vd=;var Zb,$b=Xb.prototype;
Zb={operator:{value:null},Va:{value:0,writable:!0},vb:{value:null,writable:!0},Ga:{value:null,writable:!0},J:{value:$b.J},ub:{value:$b.ub,writable:!0},Cb:{value:$b.Cb},connect:{value:$b.connect},vd:{value:$b.vd}};var Yb=function(a,b){E.call(this);this.destination=a;this.Ka=b};y(Yb,E);Yb.EMPTY=E.EMPTY;Yb.create=E.create;Yb.prototype.H=;Yb.prototype.u=function(){this.Ka.ub=!0;this.ca();E.prototype.u.call(this)};
Yb.prototype.ca=function(){var a=this.Ka;if(a){this.Ka=null;var b=a.Ga;a.Va=0;a.vb=null;a.Ga=null;b&&b.unsubscribe()}};function M(a){return function(b){if("function"!==typeof a)throw new TypeError("s");return L(b,new ac(a))}}var ac=function(a){this.C=a;this.N=void 0};ac.prototype.call=function(a,b){return b.subscribe(new bc(a,this.C,this.N))};var bc=function(a,b,c){E.call(this,a);this.C=b;this.count=0;this.N=c||this};y(bc,E);bc.EMPTY=E.EMPTY;bc.create=E.create;bc.prototype.l=function(a){try{var b=this.C.call(this.N,a,this.count++)}catch(c){this.destination.error(c);return}this.destination.next(b)};var cc="function"===typeof Symbol&&Symbol.iterator?Symbol.iterator:"@@iterator";var dc=function(a){return a&&"number"===typeof a.length&&"function"!==typeof a};function ec(a){return!!a&&"function"!==typeof a.subscribe&&"function"===typeof a.then};;var ic=;var jc=;var lc=function(a){return function(b){a.then(function(c){b.closed||(b.next(c),b.complete())},).then(null,pb);return b}};var mc=function(a){if(a&&"function"===typeof a[ob])return jc(a);if(dc(a))return Lb(a);if(ec(a))return lc(a);if(a&&"function"===typeof a[cc])return ic(a);if(Symbol&&Symbol.asyncIterator&&a&&"function"===typeof a[Symbol.asyncIterator])return gc(a);throw new TypeError("u`"+(ub(a)?"an invalid object":"'"+a+"'"));};var nc=function(a){E.call(this);this.parent=a};y(nc,E);nc.EMPTY=E.EMPTY;nc.create=E.create;nc.prototype.l=function(a){this.parent.$(a)};nc.prototype.H=;nc.prototype.u=function(){this.parent.G();this.unsubscribe()};var oc=function(a,b,c){E.call(this);this.parent=a;this.ud=b;this.Ye=c};y(oc,E);oc.EMPTY=E.EMPTY;oc.create=E.create;oc.prototype.l=function(a){this.parent.$(this.ud,a,this.Ye,this)};oc.prototype.H=;
oc.prototype.u=function(){this.parent.G(this);this.unsubscribe()};var N=function(){E.apply(this,arguments)};y(N,E);N.EMPTY=E.EMPTY;N.create=E.create;N.prototype.$=;N.prototype.ta=;N.prototype.G=;var O=function(){E.apply(this,arguments)};y(O,E);O.EMPTY=E.EMPTY;O.create=E.create;O.prototype.$=;O.prototype.ta=;
O.prototype.G=;function pc(a,b){if(!b.closed)return a instanceof I?a.subscribe(b):mc(a)(b)};var qc={};function P(){var a=z.apply(0,arguments),b=void 0,c=void 0,d=void 0;Nb(a[a.length-1])&&(c=a.pop());"function"===typeof a[a.length-1]&&(b=a.pop());if(1===a.length){var e=a[0];sb(e)&&(a=e);ub(e)&&Object.getPrototypeOf(e)===Object.prototype&&(d=Object.keys(e),a=d.map())}return L(Mb(a,c),new rc(b,d))}var rc=function(a,b){this.Kb=a;this.keys=b};rc.prototype.call=function(a,b){return b.subscribe(new sc(a,this.Kb,this.keys))};
var sc=function(a,b,c){O.call(this,a);this.Kb=b;this.keys=c;this.active=0;this.values=[];this.ua=[]};y(sc,O);sc.EMPTY=O.EMPTY;sc.create=O.create;n=sc.prototype;n.l=function(a){this.values.push(qc);this.ua.push(a)};n.u=function(){var a=this.ua,b=a.length;if(0===b)this.destination.complete();else{this.Fa=this.active=b;for(var c=0;c<b;c++)this.add(pc(a[c],new oc(this,null,c)))}};n.G=function(){0===--this.active&&this.destination.complete()};
n.$=function(a,b,c){var d=this.values,e=d[c];e=this.Fa?e===qc?--this.Fa:this.Fa:0;d[c]=b;0===e&&(this.Kb?this.Md(d):this.destination.next(this.keys?this.keys.reduce(,{}):d.slice()))};n.Md=;;;;;function xc(a){var b=yc;if(null!=a){if(a&&"function"===typeof a[ob])return vc(a,b);if(ec(a))return wc(a,b);if(dc(a))return Kb(a,b);if(a&&"function"===typeof a[cc]||"string"===typeof a)return uc(a,b);if(Symbol&&Symbol.asyncIterator&&"function"===typeof a[Symbol.asyncIterator])return tc(a,b)}throw new TypeError("w`"+(null!==a&&typeof a||a));};function zc(a){return a instanceof I?a:new I(mc(a))};function Ac(a,b){var c=void 0===c?Infinity:c;if("function"===typeof b)return ;"number"===typeof b&&(c=b);return function(d){return L(d,new Bc(a,c))}}var Bc=function(a,b){b=void 0===b?Infinity:b;this.C=a;this.cc=b};Bc.prototype.call=function(a,b){return b.subscribe(new Cc(a,this.C,this.cc))};
var Cc=function(a,b,c){c=void 0===c?Infinity:c;N.call(this,a);this.destination=a;this.C=b;this.cc=c;this.hd=!1;this.buffer=[];this.index=this.active=0};y(Cc,N);Cc.EMPTY=N.EMPTY;Cc.create=N.create;Cc.prototype.l=function(a){if(this.active<this.cc){var b=this.index++;try{var c=this.C(a,b)}catch(d){this.destination.error(d);return}this.active++;a=new nc(this);this.destination.add(a);pc(c,a)}else this.buffer.push(a)};
Cc.prototype.u=function(){this.hd=!0;0===this.active&&0===this.buffer.length&&this.destination.complete();this.unsubscribe()};Cc.prototype.$=function(a){this.destination.next(a)};Cc.prototype.G=function(){var a=this.buffer;this.active--;0<a.length?this.l(a.shift()):0===this.active&&this.hd&&this.destination.complete()};function Dc(a){a=void 0===a?Infinity:a;return Ac(Ab,a)};function Ec(){return Dc(1)(K.apply(null,w(z.apply(0,arguments))))};function Fc(a,b,c){if(tb(c)){var d=c;c=void 0}return d?Fc(a,b,c).g(M()):new I(function(e){Gc(a,b,function(f){1<arguments.length?e.next(Array.prototype.slice.call(arguments)):e.next(f)},e,c)})}
function Gc(a,b,c,d,e){if(a&&"function"===typeof a.addEventListener&&"function"===typeof a.removeEventListener){a.addEventListener(b,c,e);var f=function(){return a.removeEventListener(b,c,e)}}else if(a&&"function"===typeof a.Te&&"function"===typeof a.Se)a.Te(b,c),f=;else if(a&&"function"===typeof a.addListener&&"function"===typeof a.removeListener)a.addListener(b,c),f=;else if(a&&a.length)for(var g=0,h=a.length;g<h;g++)Gc(a[g],b,
c,d,e);else throw new TypeError("x");d.add(f)};var Hc=;y(Hc,D);Hc.EMPTY=D.EMPTY;Hc.prototype.m=;var Ic=function(a,b){D.call(this);this.K=a;this.Pb=b;this.pending=!1};y(Ic,Hc);Ic.EMPTY=Hc.EMPTY;n=Ic.prototype;n.m=;n.nb=;n.mb=;
n.execute=;n.Nc=function(a){var b=!1,c=void 0;try{this.Pb(a)}catch(d){b=!0,c=!!d&&d||Error(d)}if(b)return this.unsubscribe(),c};n.ca=function(){var a=this.id,b=this.K,c=b.actions,d=c.indexOf(this);this.state=this.Pb=null;this.pending=!1;this.K=null;-1!==d&&c.splice(d,1);null!=a&&(this.id=this.mb(b,a,null));this.delay=null};var Jc=function(a,b){b=void 0===b?Rb:b;Sb.call(this,a,);var c=this;this.actions=[];this.active=!1;this.Lb=void 0};y(Jc,Sb);Jc.prototype.m=function(a,b,c){b=void 0===b?0:b;return Jc.za&&Jc.za!==this?Jc.za.m(a,b,c):Sb.prototype.m.call(this,a,b,c)};
Jc.prototype.flush=function(a){var b=this.actions;if(this.active)b.push(a);else{var c;this.active=!0;do if(c=a.execute(a.state,a.delay))break;while(a=b.shift());this.active=!1;if(c){for(;a=b.shift();)a.unsubscribe();throw c;}}};function Kc(){var a=z.apply(0,arguments),b=Infinity,c=void 0,d=a[a.length-1];Nb(d)?(c=a.pop(),1<a.length&&"number"===typeof a[a.length-1]&&(b=a.pop())):"number"===typeof d&&(b=a.pop());return!c&&1===a.length&&a[0]instanceof I?a[0]:Dc(b)(Mb(a,c))};;var Mc=new I(Lc);function Q(a){return function(b){return L(b,new Nc(a))}}var Nc=function(a){this.S=a;this.N=void 0};Nc.prototype.call=function(a,b){return b.subscribe(new Oc(a,this.S,this.N))};var Oc=function(a,b,c){E.call(this,a);this.S=b;this.N=c;this.count=0};y(Oc,E);Oc.EMPTY=E.EMPTY;Oc.create=E.create;Oc.prototype.l=function(a){try{var b=this.S.call(this.N,a,this.count++)}catch(c){this.destination.error(c);return}b&&this.destination.next(a)};function Pc(){var a=z.apply(0,arguments);if(1===a.length)if(sb(a[0]))a=a[0];else return zc(a[0]);return L(Mb(a),new Qc)}var Qc=function(){};Qc.prototype.call=function(a,b){return b.subscribe(new Rc(a))};var Rc=function(a){O.call(this,a);this.bb=!1;this.ua=[];this.pb=[]};y(Rc,O);Rc.EMPTY=O.EMPTY;Rc.create=O.create;n=Rc.prototype;n.l=function(a){this.ua.push(a)};
n.u=function(){var a=this.ua,b=a.length;if(0===b)this.destination.complete();else{for(var c=0;c<b&&!this.bb;c++){var d=pc(a[c],new oc(this,null,c));this.pb&&this.pb.push(d);this.add(d)}this.ua=null}};n.$=;n.G=;n.ta=;(function(){a.prototype=Object.create(Error.prototype);return a})();var Sc=1,Xc,Yc={};var $c=;var ad=;y(ad,Ic);ad.EMPTY=Ic.EMPTY;ad.prototype.nb=;ad.prototype.mb=;var bd=function(){Jc.apply(this,arguments)};y(bd,Jc);bd.prototype.flush=;var cd=new bd(ad);var dd=function(a,b){Ic.call(this,a,b);this.K=a;this.Pb=b};y(dd,Ic);dd.EMPTY=Ic.EMPTY;dd.prototype.m=function(a,b){b=void 0===b?0:b;if(0<b)return Ic.prototype.m.call(this,a,b);this.delay=b;this.state=a;this.K.flush(this);return this};dd.prototype.execute=function(a,b){return 0<b||this.closed?Ic.prototype.execute.call(this,a,b):this.Nc(a,b)};dd.prototype.nb=;var ed=function(){Jc.apply(this,arguments)};y(ed,Jc);var yc=new ed(dd);(function(){a.prototype=Object.create(Error.prototype);return a})();(function(){a.prototype=Object.create(Error.prototype);return a})();(function(){a.prototype=Object.create(Error.prototype);return a})();var fd=function(){this.s=new Fa;this.h=new Ga;this.id=lb()};fd.prototype.nc=;p.Object.defineProperties(fd.prototype,{Gb:{configurable:!0,enumerable:!0,get:}});var gd=function(a,b){b=Error.call(this,b?a+": "+b:String(a));this.message=b.message;"stack"in b&&(this.stack=b.stack);this.code=a;this.__proto__=gd.prototype;this.name=String(a)};y(gd,Error);var R=function(a){gd.call(this,1E3,'sfr:"'+a+'"');this.Me=a;this.__proto__=R.prototype};y(R,gd);var hd=;y(hd,gd);var id=;y(id,gd);var jd=;
y(jd,gd);var kd=;y(kd,gd);var ld=;y(ld,gd);var md=;y(md,gd);var nd=function(a){var b=z.apply(1,arguments),c=this;this.Qa=[];this.Qa.push(a);b.forEach(function(d){c.Qa.push(d)})};nd.prototype.gb=function(a){return this.Qa.some(function(b){return b.gb(a)})};nd.prototype.ga=function(a,b){for(var c=0;c<this.Qa.length;c++)if(this.Qa[c].gb(b))return this.Qa[c].ga(a,b);throw new id;};var od=Symbol("time-origin"),pd=Symbol("date"),qd=function(a,b){this.value=a;this.timeline=b},rd=function(a,b){if(b.timeline!==a.timeline)throw new jd;return a.value-b.value};qd.prototype.equals=function(a){return 0===rd(this,a)};qd.prototype.maximum=function(a){if(a.timeline!==this.timeline)throw new jd;return this.value>=a.value?this:a};qd.prototype.round=function(){return new qd(Math.round(this.value),this.timeline)};qd.prototype.toString=function(){return String(this.value)};function sd(a){function b(c){return"boolean"===typeof c||"string"===typeof c||"number"===typeof c||void 0===c||null===c}return b(a)?!0:Array.isArray(a)?a.every(b):"object"===typeof a?Object.keys(a).every(function(c){return"string"===typeof c})&&Object.values(a).every(function(c){return Array.isArray(c)?c.every(b):b(c)}):!1}function td(a){return sd(a)?a:String(a)};var ud=function(a){ud[" "](a);return a};ud[" "]=function(){};var vd=function(a,b){try{return ud(a[b]),!0}catch(c){}return!1},xd=;var yd=C("Opera"),zd=C("Trident")||C("MSIE"),Ad=C("Edge"),Bd=C("Gecko")&&!(-1!=hb().toLowerCase().indexOf("webkit")&&!C("Edge"))&&!(C("Trident")||C("MSIE"))&&!C("Edge"),Cd=-1!=hb().toLowerCase().indexOf("webkit")&&!C("Edge"),Dd=,Ed;
a:{var Fd="",Gd=function(){var a=hb();if(Bd)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ad)return/Edge\/([\d\.]+)/.exec(a);if(zd)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Cd)return/WebKit\/(\S+)/.exec(a);if(yd)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Gd&&(Fd=Gd?Gd[1]:"");if(zd){var Hd=Dd();if(null!=Hd&&Hd>parseFloat(Fd)){Ed=String(Hd);break a}}Ed=Fd}
var Id=Ed,wd={},Jd=,Kd;
if(Aa.document&&zd){var Ld=Dd();Kd=Ld?Ld:parseInt(Id,10)||void 0}else Kd=void 0;var Md=Kd;kb();jb();ib();var Nd={},Od=null,Pd=Bd||Cd||"function"==typeof Aa.btoa,Qd=;var Rd="undefined"!==typeof Uint8Array;var Sd="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol("INTERNAL_ARRAY_STATE"):void 0;function Td(a,b){Object.isFrozen(a)||(Sd?a[Sd]|=b:void 0!==a.Hb?a.Hb|=b:Object.defineProperties(a,{Hb:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}var Ud=Object.getOwnPropertyDescriptor(Array.prototype,"Ge");
Object.defineProperties(Array.prototype,{Ge:{get:,configurable:!0,enumerable:!1}});function Vd(a){Ua(a,"state is only maintained on arrays.");a=Sd?a[Sd]:a.Hb;return null==a?0:a}function Wd(a){Ua(a,"state is only maintained on arrays.");Td(a,1);return a}function Xd(a){return Array.isArray(a)?!!(Vd(a)&2):!1}
;function Zd(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var $d,ae=Symbol("exempted jspb subclass"),be=Symbol("generated by jspb"),ce=Object.freeze(Wd([])),de="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function ee(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};;var ge=;if(de){var he=,ie={};Object.defineProperties(ge,(ie[Symbol.hasInstance]=ee(he),ie));A(ge[Symbol.hasInstance]===he,"defineProperties did not work: was it monkey-patched?")};function je(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)&&Rd&&null!=a&&a instanceof Uint8Array)return Qd(a)}return a};
;var pe=function(a,b,c){return-1===b?null:b>=a.Ca?a.X?a.X[b]:void 0:(void 0===c?0:c)&&a.X&&(c=a.X[b],null!=c)?c:a.A[b+a.xa]},qe=function(a,b,c,d){d=void 0===d?!1:d;if(Xd(a.A))throw Error("A");b<a.Ca&&!d?a.A[b+a.xa]=c:(a.X||(a.X=a.A[a.Ca+a.xa]={}))[b]=c;return a},re=function(a,b,c){a=pe(a,b);return null==a?c:a},se=function(a,b,c,d,e){if(-1===c)return null;a.F||(a.F={});var f=a.F[c];if(f)return f;e=pe(a,c,void 0===e?!1:e);if(null==e&&!d)return f;b=new b(e);Xd(a.A)&&Yd(b.A);return a.F[c]=b};var S=function(a,b,c){Xa(this,S,"The message constructor should only be used by subclasses");A(this.constructor!==S,"Message is an abstract class and cannot be directly constructed");if(!0!==this[ae]){A(!0===this[be],"Message can only be subclassed by proto gencode.");var d=Object.getPrototypeOf(A(Object.getPrototypeOf(this)));A(d.hasOwnProperty(be),"Generated jspb classes should not be extended")}a||(a=te);te=null;d=this.constructor.Yf;a||(a=d?[d]:[]);this.xa=(d?0:-1)-(this.constructor.Uf||0);this.F=
void 0;this.A=a;a:{d=this.A.length;a=d-1;if(d&&(d=this.A[a],Zd(d))){this.Ca=a-this.xa;this.X=d;break a}void 0!==b&&-1<b?(this.Ca=Math.max(b,a+1-this.xa),this.X=void 0):this.Ca=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.Ca)a+=this.xa,(d=this.A[a])?Array.isArray(d)&&Wd(d):this.A[a]=ce;else{d=this.X||(this.X=this.A[this.Ca+this.xa]={});var e=d[a];e?Array.isArray(e)&&Wd(e):d[a]=ce}};S.prototype.toJSON=function(){var a=this.A;return $d?a:ke(a,oe)};
var ve=function(a){$d=!0;try{return JSON.stringify(a.toJSON(),ue)}finally{$d=!1}};S.prototype.getExtension=;S.prototype.hasExtension=;S.prototype.clone=;S.prototype.toString=;
function ue(a,b){return je(b)}
var te;var xe=;y(xe,S);xe.prototype.clone=;if(de){var ye=,ze={};Object.defineProperties(xe,(ze[Symbol.hasInstance]=ee(ye),ze));A(xe[Symbol.hasInstance]===ye,"broken defineProperties implementation")};A(!0);var Ae=function(){S.apply(this,arguments)};y(Ae,S);if(de){var Be=,Ce={};Object.defineProperties(Ae,(Ce[Symbol.hasInstance]=ee(Be),Ce));A(Ae[Symbol.hasInstance]===Be,"defineProperties did not work: was it monkey-patched?")};var De=function(){Ae.apply(this,arguments)};y(De,Ae);De.prototype[be]=!0;if(de){var Ee={};Object.defineProperties(De,(Ee[Symbol.hasInstance]=ee(Object[Symbol.hasInstance]),Ee));A(De[Symbol.hasInstance]===Object[Symbol.hasInstance],"broken defineProperties implementation")};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Fe=function(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0};n=Fe.prototype;n.clone=;n.toString=;n.equals=;n.ceil=;n.floor=;
n.round=;n.translate=;n.scale=;var Ge=function(a,b){this.width=a;this.height=b};n=Ge.prototype;n.clone=;n.toString=;n.aspectRatio=;n.uc=;n.ceil=;n.floor=;
n.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};n.scale=;var Je=function(a){return a?new He(Ie(a)):La||(La=new He)},Ke=function(a){var b=a.scrollingElement?a.scrollingElement:Cd||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement;a=a.parentWindow||a.defaultView;return zd&&Jd()&&a.pageYOffset!=b.scrollTop?new Fe(b.scrollLeft,b.scrollTop):new Fe(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)},Le=,Ie=function(a){A(a,"Node cannot be null or undefined.");return 9==a.nodeType?a:a.ownerDocument||a.document},Me=,He=function(a){this.Ma=a||Aa.document||
document};n=He.prototype;n.getElementsByTagName=;n.createElement=;n.createTextNode=;n.appendChild=;n.append=;
n.canHaveChildren=;n.removeNode=;
n.contains=;var Oe=function(){return!Ne()&&(C("iPod")||C("iPhone")||C("Android")||C("IEMobile"))},Ne=function(){return C("iPad")||C("Android")&&!C("Mobile")||C("Silk")};var Pe=function(a){try{return!!a&&null!=a.location.href&&vd(a,"foo")}catch(b){return!1}};var Qe=function(){var a=void 0===a?Aa:a;return(a=a.performance)&&a.now?a.now():null};var Re=function(a,b){var c=window;return function(){var d=Qe(),e=3;try{var f=b.apply(this,arguments)}catch(h){throw e=13,h;}finally{if(c.google_measure_js_timing&&d){var g=Qe()||0;d={label:a.toString(),value:d,duration:g-d,type:e};e=c.google_js_reporting_queue=c.google_js_reporting_queue||[];2048>e.length&&e.push(d)}}return f}};var Se=function(){Fa.apply(this,arguments)};y(Se,Fa);Se.prototype.ja=function(a,b){return Fa.prototype.ja.call(this,a,Re(a,b))};function Te(a,b){return function(c){return new I(function(d){return c.subscribe(function(e){a.ja(b,function(){d.next(e)})()},,)})}};var Ue=function(a,b,c){this.context=a;this.kb=b;this.sd=c};Ue.prototype.gb=function(a){return(void 0===a||a===this.sd)&&this.kb.xb};Ue.prototype.ga=function(a,b){if(!this.gb(b))throw new id;return new Ve(this.context,this.kb,this.sd,a)};var Ve=function(a,b,c,d){var e=this;this.kb=b;this.method=c;this.url=d;this.Aa="pending";this.Wd=a.nc().subscribe()};Ve.prototype.deactivate=;
Ve.prototype.sendNow=function(){if("pending"===this.Aa)if(this.Wd.unsubscribe(),this.kb.xb){this.Aa="sending";try{this.kb.ping(this.url)}catch(a){this.Aa="failed"}this.Aa="sent"}else this.Aa="failed"};p.Object.defineProperties(Ve.prototype,{state:{configurable:!0,enumerable:!0,get:}});var Xe=function(){for(var a=u(z.apply(0,arguments)),b=a.next();!b.done;b=a.next())if(b=b.value,b.da()){this.i=b;return}this.i=new We};n=Xe.prototype;n.da=function(){return this.i.da()};n.now=function(){return this.i.now()};n.setTimeout=function(a,b){return this.i.setTimeout(a,b)};n.clearTimeout=;n.interval=function(a){return this.i.interval(a)};p.Object.defineProperties(Xe.prototype,{timeline:{configurable:!0,enumerable:!0,get:function(){return this.i.timeline}}});
var We=;n=We.prototype;n.da=;n.now=;n.setTimeout=;n.clearTimeout=;n.interval=;var Ye=function(a,b){this.B=a;this.s=b};Ye.prototype.setTimeout=function(a,b){return this.B.setTimeout(this.s.ja(734,a),b)};Ye.prototype.clearTimeout=;Ye.prototype.interval=function(a){var b=this;return new I()};Ye.prototype.da=function(){return!!this.B.clearTimeout&&!!this.B.setTimeout&&!!this.B.setInterval&&!!this.B.clearInterval};var Ze=function(a,b){Ye.call(this,a,b);this.timeline=pd};y(Ze,Ye);Ze.prototype.now=;Ze.prototype.da=;var $e=function(a,b){Ye.call(this,a,b);this.timeline=od};y($e,Ye);$e.prototype.now=function(){return new qd(this.B.performance.now(),this.timeline)};$e.prototype.da=function(){return!!this.B.performance&&!!this.B.performance.now&&Ye.prototype.da.call(this)};function af(a,b){var c=!1;return new I(function(d){var e=a.setTimeout(,b);return })};function bf(a){return function(b){var c=new cf(a);b=L(b,c);return c.bc=b}}var cf=function(a){this.Ec=a};cf.prototype.call=function(a,b){return b.subscribe(new df(a,this.Ec,this.bc))};var df=function(a,b,c){N.call(this,a);this.Ec=b;this.bc=c};y(df,N);df.EMPTY=N.EMPTY;df.create=N.create;df.prototype.error=;function ef(){var a=z.apply(0,arguments),b=void 0;"function"===typeof a[a.length-1]&&(b=a.pop());1===a.length&&sb(a[0])&&(a=a[0].slice());return function(c){var d=zc([c].concat(w(a))),e=new rc(b);if(c&&"function"===typeof c.hb)c=c.hb.call(d,e);else throw new TypeError("r");return c}}function ff(){return ef.apply(null,w(z.apply(0,arguments)))};var hf=;hf.prototype.call=;var jf=;y(jf,E);jf.EMPTY=E.EMPTY;jf.create=E.create;jf.prototype.l=;jf.prototype.u=;function kf(a){return function(b){return L(b,new lf(a))}}var lf=function(a){this.ic=a};lf.prototype.call=;var mf=;y(mf,O);mf.EMPTY=O.EMPTY;mf.create=O.create;n=mf.prototype;n.$=;n.ta=;n.G=;
n.l=;n.u=;var nf=,of=;function pf(a){return function(b){return L(b,new qf(a))}}var qf=function(a){this.ra=a;this.re=void 0};qf.prototype.call=function(a,b){return b.subscribe(new rf(a,this.ra,this.re))};var rf=function(a,b,c){N.call(this,a);this.ra=b;this.values=new Set;c&&this.add(pc(c,new nc(this)))};y(rf,N);rf.EMPTY=N.EMPTY;rf.create=N.create;n=rf.prototype;n.$=;n.ta=;n.l=function(a){this.ra?this.Od(a):this.Oc(a,a)};
n.Od=function(a){var b=this.destination;try{var c=this.ra(a)}catch(d){b.error(d);return}this.Oc(c,a)};n.Oc=function(a,b){var c=this.values;c.has(a)||(c.add(a),this.destination.next(b))};function T(a){return function(b){return L(b,new sf(a))}}var sf=function(a){this.compare=a;this.ra=void 0};sf.prototype.call=function(a,b){return b.subscribe(new tf(a,this.compare,this.ra))};var tf=function(a,b,c){E.call(this,a);this.ra=c;this.kd=!1;"function"===typeof b&&(this.compare=b)};y(tf,E);tf.EMPTY=E.EMPTY;tf.create=E.create;tf.prototype.compare=function(a,b){return a===b};
tf.prototype.l=function(a){try{var b=this.ra;var c=b?b(a):a}catch(e){return this.destination.error(e)}b=!1;if(this.kd)try{var d=this.compare;b=d(this.key,c)}catch(e){return this.destination.error(e)}else this.kd=!0;b||(this.key=c,this.destination.next(a))};function uf(){if(isNaN(1))throw new TypeError("I");return function(a){return L(a,new vf)}}var vf=function(){this.count=1};vf.prototype.call=function(a,b){return b.subscribe(new wf(a,this.count))};var wf=function(a,b){E.call(this,a);this.count=b;this.Pd=0};y(wf,E);wf.EMPTY=E.EMPTY;wf.create=E.create;wf.prototype.l=function(a){var b=this.count,c=++this.Pd;c<=b&&(this.destination.next(a),c===b&&(this.destination.complete(),this.unsubscribe()))};function xf(a){a=void 0===a?yf:a;return function(b){return L(b,new zf(a))}}var zf=function(a){this.kc=a};zf.prototype.call=;var Af=;y(Af,E);Af.EMPTY=E.EMPTY;Af.create=E.create;Af.prototype.l=;Af.prototype.u=;
;function Bf(){var a=z.apply(0,arguments);return function(b){return Ec(b,K.apply(null,w(a)))}};function Cf(a){return function(b){return L(b,new Df(a,b))}}var Df=function(a,b){this.S=a;this.N=void 0;this.source=b};Df.prototype.call=;var Ef=;y(Ef,E);Ef.EMPTY=E.EMPTY;Ef.create=E.create;Ef.prototype.G=;
Ef.prototype.l=;Ef.prototype.u=;function Ff(){return function(a){return L(a,new Gf)}}var Gf=function(){};Gf.prototype.call=function(a,b){return b.subscribe(new Hf(a))};var Hf=function(){E.apply(this,arguments)};y(Hf,E);Hf.EMPTY=E.EMPTY;Hf.create=E.create;Hf.prototype.l=function(){};function If(){if(isNaN(1))throw new TypeError("I");return function(a){return L(a,new Jf)}}var Jf=function(){this.total=1};Jf.prototype.call=;var Kf=;y(Kf,E);Kf.EMPTY=E.EMPTY;Kf.create=E.create;Kf.prototype.l=;
Kf.prototype.u=;function Lf(a,b){var c=2<=arguments.length;return function(d){return d.g(a?Q():Ab,If(),c?gf(b):xf())}};function Mf(a){return function(b){return L(b,new Nf(a))}}var Nf=function(a){this.value=a};Nf.prototype.call=function(a,b){return b.subscribe(new Of(a,this.value))};var Of=function(a,b){E.call(this,a);this.value=b};y(Of,E);Of.EMPTY=E.EMPTY;Of.create=E.create;Of.prototype.l=function(){this.destination.next(this.value)};function Pf(a,b){var c=!1;2<=arguments.length&&(c=!0);return function(d){return L(d,new Qf(a,b,c))}}var Qf=function(a,b,c){this.Yb=a;this.seed=b;this.we=void 0===c?!1:c};Qf.prototype.call=function(a,b){return b.subscribe(new Rf(a,this.Yb,this.seed,this.we))};var Rf=function(a,b,c,d){E.call(this,a);this.Yb=b;this.Sb=c;this.Qc=d;this.index=0};y(Rf,E);Rf.EMPTY=E.EMPTY;Rf.create=E.create;
Rf.prototype.l=function(a){var b=this.destination;if(this.Qc){var c=this.index++;try{var d=this.Yb(this.Sb,a,c)}catch(e){b.error(e);return}this.Sb=d;b.next(d)}else this.Sb=a,this.Qc=!0,b.next(a)};function Sf(a){return function(b){var c="function"===typeof a?a:function(){return a};var d=Object.create(b,Zb);d.source=b;d.Cd=c;return d}};function Tf(){var a=z.apply(0,arguments);1===a.length&&sb(a[0])&&(a=a[0]);return function(b){return L(b,new Uf(a))}}var Uf=function(a){this.yc=a};Uf.prototype.call=function(a,b){return b.subscribe(new Vf(a,this.yc))};var Vf=function(a,b){N.call(this,a);this.destination=a;this.yc=b};y(Vf,N);Vf.EMPTY=N.EMPTY;Vf.create=N.create;Vf.prototype.ta=;Vf.prototype.G=;Vf.prototype.H=;Vf.prototype.u=;
var Wf=;function Xf(){var a=new Qb(1,void 0,void 0);return function(b){return Sf(function(){return a})(b)}};function Yf(){return new J}function Zf(){return function(a){return Ub()(Sf(Yf)(a))}};function U(){var a=z.apply(0,arguments),b=a[a.length-1];return Nb(b)?(a.pop(),):function(c){return Ec(a,c)}};var $f=function(a,b,c){b=void 0===b?0:b;c=void 0===c?cd:c;this.source=a;this.delayTime=b;this.K=c;0>b&&(this.delayTime=0);Nb(c)||(this.K=cd)};y($f,I);$f.create=I.create;$f.ge=function(a){return this.add(a.source.subscribe(a.Gc))};$f.prototype.J=function(a){return this.K.m($f.ge,this.delayTime,{source:this.source,Gc:a})};function ag(){var a=void 0===a?0:a;return function(b){return L(b,new bg(a))}}var bg=function(a){this.K=yc;this.delay=a};
bg.prototype.call=function(a,b){return(new $f(b,this.delay,this.K)).subscribe(a)};function V(a){return function(b){return L(b,new cg(a))}}var cg=function(a){this.C=a};cg.prototype.call=function(a,b){return b.subscribe(new dg(a,this.C))};var dg=function(a,b){N.call(this,a);this.destination=a;this.C=b;this.index=0};y(dg,N);dg.EMPTY=N.EMPTY;dg.create=N.create;n=dg.prototype;n.l=function(a){var b=this.index++;try{var c=this.C(a,b)}catch(d){this.destination.error(d);return}(a=this.Fb)&&a.unsubscribe();a=new nc(this);this.destination.add(a);this.Fb=a;pc(c,a)};
n.u=function(){var a=this.Fb;a&&!a.closed||N.prototype.u.call(this);this.unsubscribe()};n.ca=function(){this.Fb=void 0};n.G=function(){this.Fb=void 0;this.o&&N.prototype.u.call(this)};n.$=function(a){this.destination.next(a)};function eg(a,b){b=void 0===b?!1:b;return function(c){return L(c,new fg(a,b))}}var fg=function(a,b){this.S=a;this.qc=b};fg.prototype.call=function(a,b){return b.subscribe(new gg(a,this.S,this.qc))};var gg=function(a,b,c){E.call(this,a);this.S=b;this.qc=c;this.index=0};y(gg,E);gg.EMPTY=E.EMPTY;gg.create=E.create;gg.prototype.l=function(a){var b=this.destination;try{var c=this.S(a,this.index++)}catch(d){b.error(d);return}b=this.destination;c?b.next(a):(this.qc&&b.next(a),b.complete())};function hg(a,b,c){return function(d){return L(d,new ig(a,b,c))}}var ig=function(a,b,c){this.Oe=a;this.error=b;this.complete=c};ig.prototype.call=function(a,b){return b.subscribe(new jg(a,this.Oe,this.error,this.complete))};var jg=function(a,b,c,d){E.call(this,a);this.Tb=this.Ub=this.Vb=Lc;this.Ub=c||Lc;this.Tb=d||Lc;tb(b)?(this.ba=this,this.Vb=b):b&&(this.ba=b,this.Vb=b.next||Lc,this.Ub=b.error||Lc,this.Tb=b.complete||Lc)};y(jg,E);jg.EMPTY=E.EMPTY;jg.create=E.create;
jg.prototype.l=function(a){try{this.Vb.call(this.ba,a)}catch(b){this.destination.error(b);return}this.destination.next(a)};jg.prototype.H=;jg.prototype.u=function(){try{this.Tb.call(this.ba)}catch(a){this.destination.error(a);return}return this.destination.complete()};function kg(){var a=z.apply(0,arguments);return function(b){var c;"function"===typeof a[a.length-1]&&(c=a.pop());return L(b,new lg(a,c))}}var lg=function(a,b){this.ua=a;this.C=b};lg.prototype.call=function(a,b){return b.subscribe(new mg(a,this.ua,this.C))};var mg=function(a,b,c){O.call(this,a);this.C=c;this.Fa=[];a=b.length;this.values=Array(a);for(c=0;c<a;c++)this.Fa.push(c);for(c=0;c<a;c++)this.add(pc(b[c],new oc(this,void 0,c)))};y(mg,O);mg.EMPTY=O.EMPTY;mg.create=O.create;
mg.prototype.$=function(a,b,c){this.values[c]=b;b=this.Fa;0<b.length&&(c=b.indexOf(c),-1!==c&&b.splice(c,1))};mg.prototype.G=function(){};mg.prototype.l=function(a){0===this.Fa.length&&(a=[a].concat(w(this.values)),this.C?this.Ld(a):this.destination.next(a))};mg.prototype.Ld=;var ng=function(a){this.global=a=void 0===a?window:a};ng.prototype.ping=function(){var a=this;return Kc.apply(null,w(z.apply(0,arguments).map(function(b){return zc(a.global.fetch(b,{method:"GET",cache:"no-cache",keepalive:!0,mode:"no-cors"})).g(M())}))).g(Cf(),Lf())};p.Object.defineProperties(ng.prototype,{xb:{configurable:!0,enumerable:!0,get:function(){return!!this.global.fetch}}});var og=function(a){this.global=a=void 0===a?window:a};og.prototype.ping=;p.Object.defineProperties(og.prototype,{xb:{configurable:!0,enumerable:!0,get:}});var pg=function(a){this.global=a=void 0===a?window:a};pg.prototype.ping=;p.Object.defineProperties(pg.prototype,{xb:{configurable:!0,enumerable:!0,get:}});function qg(a){return function(b){return b.g(rg(a,Sf(new J)))}}function W(a){return function(b){return b.g(rg(a,Xf()))}}function rg(a,b){function c(d){return new I(function(e){return d.subscribe(function(f){Ha(a,function(){return void e.next(f)})},,function(){Ha(a,function(){return void e.complete()})})})}return G(c,ag(),b,Ub(),c)};var X=function(a){this.value=a};X.prototype.ya=function(a){return K(this.value).g(W(a))};var sg=new X(!0);function tg(a){var b=ug(a);return null===b?new X(null):b.g(M(function(c){c=ve(c);if(Pd)c=Aa.btoa(c);else{for(var d=[],e=0,f=0;f<c.length;f++){var g=c.charCodeAt(f);255<g&&(d[e++]=g&255,g>>=8);d[e++]=g}c=Qd(d)}return c}),uf(),W(a.h))};;var wg=["FRAME","IMG","IFRAME"],yg=/^[01](px)?$/;function zg(a){return"string"===typeof a?document.getElementById(a):a}
function Ag(a,b){var c=!0,d=!0,e=void 0,f=!0;c=void 0===c?!0:c;d=void 0===d?!1:d;f=void 0===f?!1:f;if(a=zg(a)){e||(e=function(la,fc,ma){la.addEventListener(fc,ma)});for(var g=!1,h=function(la){g||(g=!0,b(la))},k,l,m=0;m<wg.length;++m)if(wg[m]==a.tagName){l=3;k=[a];break}k||(k=a.querySelectorAll(wg.join(",")),l=2);var t=0,q=0,H=a=!1;m={};for(var F=0;F<k.length;m={sb:m.sb},F++){var v=k[F];if(!("IMG"!=v.tagName||!v.complete||v.naturalWidth&&v.naturalHeight?yg.test(v.getAttribute("width"))&&yg.test(v.getAttribute("height")):
1)){if("IMG"==v.tagName)var x=v.naturalWidth&&v.naturalHeight?!0:!1;else try{x="complete"===(v.readyState?v.readyState:v.contentWindow&&v.contentWindow.document&&v.contentWindow.document.readyState)?!0:!1}catch(la){x=void 0===d?!1:d}if(x)a=!0;else{t++;m.sb="IMG"===v.tagName;var B=function(la){return function(){t--;t||h(l);la.sb&&(q--,!q&&H&&h(l))}}(m);e(v,"load",B);m.sb&&(q++,e(v,"error",B))}}}k=null;if(0===t&&!a&&"complete"===Aa.document.readyState)l=5;else if(t||!a){e(Aa,"load",function(){f&&q?
H=!0:h(4)});return}c&&h(l)}};
function Fg(a,b,c){try{var d=JSON.parse(c.data)}catch(g){}if("object"===typeof d&&d&&"creativeLoad"===d.type){var e=Eg(a);if(c.source&&e){var f;Cg(c.source,);f&&Dg(a,)}}}function Gg(a){return"string"===typeof a?document.getElementById(a):a}
var Hg=function(a,b){var c=Gg(a);if(c)if(c.onCreativeLoad)c.onCreativeLoad(b);else{var d=b?[b]:[],e=;c.onCreativeLoad=;c.setAttribute("data-creative-load-listener","");c.addEventListener("creativeLoad",);Aa.addEventListener("message",function(f){Fg(c,e,f)})}};var Ig=function(a,b){var c=this;this.global=a;this.zc=b;this.Xe=this.document?Kc(K(!0),Fc(this.document,"visibilitychange")).g(Te(this.zc.s,748),M(function(){return c.document?c.document.visibilityState:"visible"}),T()):K("visible");this.Ue=this.document?Fc(this.document,"DOMContentLoaded").g(Te(this.zc.s,739),uf()):K(vg("DOMContentLoaded"))},Jg=,Kg=function(a){return null!==a.document&&void 0!==a.document.visibilityState};
Ig.prototype.querySelector=;Ig.prototype.querySelectorAll=function(a){return this.document?ab(this.document.querySelectorAll(a)):[]};var Lg=;Ig.prototype.elementFromPoint=;
var Mg=function(a,b,c){c=void 0===c?!1:c;if(!a.document)return K(b);var d=new Qb(1),e=function(){d.next(b)};c||Hg(b,e);Ag(b,e);return d.g(Te(a.zc.s,749),uf())};p.Object.defineProperties(Ig.prototype,{document:{configurable:!0,enumerable:!0,get:function(){return vd(this.global,"document")?this.global.document||null:null}}});var Ng={left:0,top:0,width:0,height:0};function Og(a,b){return a.left===b.left&&a.top===b.top&&a.width===b.width&&a.height===b.height}function Qg(a,b){return{left:Math.round(a.left+b.x),top:Math.round(a.top+b.y),width:a.width,height:a.height}};var Rg=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};n=Rg.prototype;n.oc=function(){return this.right-this.left};n.lc=function(){return this.bottom-this.top};n.clone=;n.toString=;
n.contains=;n.expand=;
n.ceil=;n.floor=;n.round=;
n.translate=;n.scale=;var Sg=new function(a,b){this.pe=a;this.defaultValue=void 0===b?!1:b}(434462125,!0);var Tg=[],Vg=function(){var a=Ug;A(!Object.isSealed(a),"Cannot use getInstance() with a sealed constructor.");var b="sc";if(a.sc&&a.hasOwnProperty(b))return a.sc;Tg.push(a);var c=new a;a.sc=c;A(a.hasOwnProperty(b),"Could not instantiate singleton.");return c};var Ug=function(){var a={};this.te=function(){var b=Sg.pe,c=Sg.defaultValue;return null!=a[b]?Va(a[b]):c}};var Xg=function(a){De.call(this,a,-1,Wg)};y(Xg,De);
var Yg=function(a,b){return qe(a,2,b)},Zg=function(a,b){return qe(a,3,b)},$g=function(a,b){return qe(a,4,b)},ah=function(a,b){return qe(a,5,b)},bh=function(a,b){return qe(a,9,b)},dh=function(a,b){var c=ch;var d=void 0===d?!1:d;if(Xd(a.A))throw Error("A");if(b){var e=Wd([]);for(var f=0;f<b.length;f++){var g=e,h=f,k=b[f],l=Oa(c);if(!(k instanceof l))throw Error("B`"+fe(l)+"`"+(k&&fe(k.constructor)));g[h]=k.A}a.F||(a.F={});a.F[10]=b}else a.F&&(a.F[10]=void 0),e=ce;return qe(a,10,e,d)},eh=function(a,
b){return qe(a,11,b)},fh=function(a,b){return qe(a,1,b)},ch=function(a){De.call(this,a)};y(ch,De);ch.prototype.gd=;var Wg=[10,6];var gh="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function hh(a){var b;return null!=(b=a.google_tag_data)?b:a.google_tag_data={}}
function ih(a){var b,c;if("function"!==typeof(null==(b=a.navigator)?void 0:null==(c=b.userAgentData)?void 0:c.getHighEntropyValues))return null;var d=hh(a);if(d.uach_promise)return d.uach_promise;a=a.navigator.userAgentData.getHighEntropyValues(gh).then(function(e){null!=d.uach||(d.uach=e);return e});return d.uach_promise=a}
function jh(a){var b;return eh(dh(bh(ah($g(Zg(Yg(fh(new Xg,a.platform||""),a.platformVersion||""),a.architecture||""),a.model||""),a.uaFullVersion||""),a.bitness||""),(null==(b=a.fullVersionList)?void 0:b.map(function(c){var d=new ch;d=qe(d,1,c.brand);return qe(d,2,c.version)}))||[]),a.wow64||!1)}
function kh(a){if(Vg().te()){var b,c;return null!=(c=null==(b=ih(a))?void 0:b.then(function(g){return jh(g)}))?c:null}var d,e;if("function"!==typeof(null==(d=a.navigator)?void 0:null==(e=d.userAgentData)?void 0:e.getHighEntropyValues))return null;var f;return null!=(f=a.navigator.userAgentData.getHighEntropyValues(gh).then())?f:null};var lh=function(a,b){a=void 0===a?window:a;b=void 0===b?null:b;fd.call(this);this.global=a;this.La=b;this.Ve=Fc(this.global,"pagehide").g(Te(this.s,941));this.td=Fc(this.global,"load").g(Te(this.s,738),uf());this.We=Fc(this.global,"resize").g(Te(this.s,741));this.onMessage=Fc(this.global,"message").g(Te(this.s,740));this.document=new Ig(this.global,this);this.s=new Se;this.i=new Xe(new $e(this.B,this.s),new Ze(this.B,this.s));this.I=new nd(new Ue(this,new ng(this.global),"GET"),new Ue(this,new pg(this.global),
"POST"),new Ue(this,new og(this.global),"GET"))};y(lh,fd);lh.prototype.nc=function(){return this.Ve.g(Te(this.s,942),W(this.h),M())};var mh=function(a){var b=new lh(a.global.top,a.La);b.I=a.I;return b},nh=function(a,b){b.start();return Fc(b,"message").g(Te(a.s,740))};lh.prototype.postMessage=function(a,b,c){c=void 0===c?[]:c;this.global.postMessage(a,b,c)};lh.prototype.oc=;
lh.prototype.lc=;
var oh=function(a,b){try{var c=a.global,d=Ne()||Oe();try{b&&(c=c.top);a=c;d=void 0===d?!1:d;b&&null!==a&&a!=a.top&&(a=a.top);try{if(void 0===d?0:d)var e=(new Ge(a.innerWidth,a.innerHeight)).round();else{var f=(a||window).document,g="CSS1Compat"==f.compatMode?f.documentElement:f.body;e=(new Ge(g.clientWidth,g.clientHeight)).round()}var h=e}catch(q){h=new Ge(-12245933,-12245933)}b=h;var k=Ke(Je(c.document).Ma);if(-12245933==b.width){var l=b.width;var m=new Rg(l,l,l,l)}else m=new Rg(k.y,k.x+b.width,
k.y+b.height,k.x);var t=m}catch(q){t=new Rg(-12245933,-12245933,-12245933,-12245933)}return{left:t.left,top:t.top,width:t.oc(),height:t.lc()}}catch(q){return Ng}};lh.prototype.validate=function(){return this.global&&this.i.da()&&this.I.gb()};var ug=function(a){return(a=kh(a.global))?zc(a):null};
p.Object.defineProperties(lh.prototype,{B:{configurable:!0,enumerable:!0,get:function(){return window}},Oa:{configurable:!0,enumerable:!0,get:function(){return!Pe(this.global.top)}},pc:{configurable:!0,enumerable:!0,get:function(){return this.Oa||this.global.top!==this.global}},scrollY:{configurable:!0,enumerable:!0,get:},MutationObserver:{configurable:!0,enumerable:!0,get:function(){return this.B.MutationObserver}},ResizeObserver:{configurable:!0,enumerable:!0,
get:function(){return this.B.ResizeObserver}},Ee:{configurable:!0,enumerable:!0,get:},$d:{configurable:!0,enumerable:!0,get:function(){return"vu"in this.global||"vv"in this.global}}});var ph=!zd&&!ib(),qh=function(a,b){if(/-[a-z]/.test(b))return null;if(ph&&a.dataset){if(kb()&&!(b in a.dataset))return null;a=a.dataset[b];return void 0===a?null:a}return a.getAttribute("data-"+String(b).replace(/([A-Z])/g,"-$1").toLowerCase())};var Y={},rh=(Y["data-google-av-cxn"]="_avicxn_",Y["data-google-av-cpmav"]="_cvu_",Y["data-google-av-metadata"]="_avm_",Y["data-google-av-adk"]="_adk_",Y["data-google-av-btr"]=void 0,Y["data-google-av-override"]=void 0,Y["data-google-av-dm"]=void 0,Y["data-google-av-immediate"]=void 0,Y["data-google-av-aid"]=void 0,Y["data-google-av-naid"]=void 0,Y["data-google-av-inapp"]=void 0,Y["data-google-av-slift"]=void 0,Y["data-google-av-itpl"]=void 0,Y["data-google-av-ext-cxn"]=void 0,Y["data-google-av-rs"]=
void 0,Y["data-google-av-flags"]=void 0,Y),Z={},sh=(Z["data-google-av-adk"]="googleAvAdk",Z["data-google-av-btr"]="googleAvBtr",Z["data-google-av-cpmav"]="googleAvCpmav",Z["data-google-av-dm"]="googleAvDm",Z["data-google-av-ext-cxn"]="googleAvExtCxn",Z["data-google-av-immediate"]="googleAvImmediate",Z["data-google-av-inapp"]="googleAvInapp",Z["data-google-av-itpl"]="googleAvItpl",Z["data-google-av-metadata"]="googleAvMetadata",Z["data-google-av-naid"]="googleAvNaid",Z["data-google-av-override"]="googleAvOverride",
Z["data-google-av-rs"]="googleAvRs",Z["data-google-av-slift"]="googleAvSlift",Z["data-google-av-cxn"]="googleAvCxn",Z["data-google-av-aid"]=void 0,Z["data-google-av-flags"]="googleAvFlags",Z);function th(a,b){try{var c=a.getAttribute(b);if(null!==c)return c}catch(f){}try{var d=rh[b];if(d&&(c=a[d],void 0!==c))return c}catch(f){}try{var e=sh[b];if(e)return qh(a,e)}catch(f){}return null}function uh(a){return M(function(b){return th(b,a)})};var vh=G(uh("data-google-av-cxn"),M(function(a){if(!a)throw new kd;return a.split("|")}));var wh=function(){return G(Ac(function(a){return a.element.g(vh,bf()).g(M(function(b){return{ma:b,Ab:a}}))}),pf(function(a){return a.ma.sort().join(";")}),M(function(a){return a.Ab}))};var yh=function(){return Ac(function(a){return zc(xh(a)).g(qg(a.h))})},xh=function(a){return a.document.querySelectorAll(".GoogleActiveViewElement,.GoogleActiveViewClass")};function zh(a){var b=a.td,c=a.document.Ue;return Kc(K({}),c,b).g(M(function(){return a}))};var Bh=M(Ah);function Ah(a){var b=Number(th(a,"data-google-av-rs"));return isNaN(b)||0===b?(a=a.id)?0==a.lastIndexOf("DfaVisibilityIdentifier",0)?6:0==a.lastIndexOf("YtKevlarVisibilityIdentifier",0)?15:0==a.lastIndexOf("YtSparklesVisibilityIdentifier",0)?17:0==a.lastIndexOf("YtKabukiVisibilityIdentifier",0)?18:0:0:b};function Ch(a,b){b=void 0===b?Jb:b;return Kc(zh(a),b).g(yh(),pf(),W(a.h))};function Dh(a,b){return new I(function(c){var d=!1,e=Array(b.length);e.fill(void 0);var f=new Set,g=new Set,h=[];b.forEach(function(k,l){h.push(k.subscribe(function(m){a.xd?(e[l]=m,f.add(l),d||(d=!0,Ja(a,function(){d=!1;c.next(ab(e))}))):c.error(new ld(l))},,function(){g.add(l);Ja(a,function(){g.size===b.length&&c.complete()})}))})})};function Eh(a,b,c){function d(){if(b.La){var v=b.La,x=v.next;var B={Kf:c,bg:e,cg:Object.assign({},f),Sf:g,errorMessage:h,Nf:k};B={hf:1,jf:0,kf:0,timestamp:rd(b.i.now(),new qd(0,b.i.timeline)),Gb:b.Gb,messageType:2,Lf:B};x.call(v,B)}}for(var e=Object.keys(a),f={},g=!1,h=null,k=null,l={},m=new Set,t=[],q={},H=u(e),F=H.next();!F.done;q={O:q.O},F=H.next())q.O=F.value,F=a[q.O],F instanceof X?(l[q.O]=F.value,m.add(q.O),f[String(q.O)]=td(F.value)):(F=F.g(T(),M(function(v){return function(x){f[String(v.O)]=
td(x);d();var B={};return B[v.O]=x,B}}(q)),hg(function(v){return function(){m.add(v.O)}}(q),function(v){return }(q),function(v){return function(){m.has(v.O)||(g=!0,d())}}(q))),t.push(F));(a=0<Object.keys(f).length)&&d();q=Dh(b.h,t).g(bf(),M(function(v){return Object.freeze(Object.assign.apply(Object,[{},l].concat(w(v))))}));return(t=0<t.length)&&a?Kc(K(Object.freeze(l)),q):t?q:K(Object.freeze(l))}
;function Fh(a,b,c,d){var e=Gh(Hh(Gh(Ih,Jh),Kh),Lh,Mh);return a.s.ja.bind(a.s)(733,function(){function f(){if(a.La){var l=a.La,m=l.next;var t={Wf:[].concat(w(h.values())),Rf:k};t={hf:1,jf:0,kf:0,timestamp:rd(a.i.now(),new qd(0,a.i.timeline)),Gb:a.Gb,messageType:1,Tf:t};m.call(l,t)}}var g={},h=new Set,k=!1;try{return b.g(bf(),hg(function(){},,),Ac(function(l){h.add(l.$a);f();try{var m=c(a,l)}catch(q){return d(Object.assign({},
g,{error:q instanceof Error?q:String(q)})),Jb}var t={};return Eh(m,a,l.$a).g(hg(function(q){t=q}),Xf(),Ub()).g(e,bf(),Bf(void 0),M())})).g(Pf(,0),bf())}catch(l){return d(Object.assign({},g,{error:l})),Jb}})()};var Lh=G(M(function(a){var b=a.I,c=a.$b,d=a.Jc;return void 0===b||void 0===c||void 0===d?!1:a.Ce?(d(c,a).forEach(function(e){b.ga(e).sendNow()}),!0):void 0!==a.jc?!0:!1}),eg(function(a){return!a}),Ff());function Nh(a,b){var c=Oh,d=Ph,e=Qh;b=void 0===b?.01:b;return }
;var Mh=G(M(function(a){var b=a.I,c=a.oe;if(void 0===b||void 0===c)return!1;if(void 0!==a.jc)return!0;if(null===c)return!1;for(a=0;a<c;a++)b.ga("https://pagead2.googlesyndication.com/pagead/gen_204?id=av-js&type=extra&rnd="+Math.floor(1E7*Math.random())).sendNow();return!0}),eg(function(a){return!a}),Ff());var Qh=;function Gh(){var a=z.apply(0,arguments);return function(b){var c=b.g(Xf(),Ub());b=a.map(function(d){return c.g(d,Bf(!0))});return P(b).g(uf(),Ff())}};function Hh(){var a=z.apply(0,arguments);return function(b){var c=b.g(Xf(),Ub());b=a.map(function(d){return c.g(d,Bf(!0))});return Kc.apply(null,w(b)).g(uf(),Ff())}};var Jh=G(Q(function(a){var b=a.fd,c=a.jd;return!!a.rb&&!!b&&!!c}),M(),eg(),Ff());function Rh(a){return function(b){return b.g(M(function(c){a.xd||Pa("Assertion on queued Observable output failed");return c}))}};function Sh(a){return function(b){return new I(function(c){var d=!1,e=b.g(Rh(a)).subscribe(function(f){d=!0;c.next(f)},c.error.bind(c),c.complete.bind(c));Ha(a,function(){d||c.next(null)});return e})}};function Th(a,b){return function(c){return c.g(V(function(d){return new I(function(e){var f=a.MutationObserver;if(f){var g=new f(function(h){e.next(h)});g.observe(d,b);return }})}))}};var Uh={Ff:0,wf:1,yf:2,xf:3,0:"UNKNOWN",1:"DEFER_MEASUREMENT",2:"DO_NOT_DEFER_MEASUREMENT",3:"DEFER_MEASUREMENT_AND_PING"};function Vh(a,b){var c=b.g(Th(a,{attributes:!0}),W(a.h));return P([b,c.g(W(a.h),Sh(a.h))]).g(M(function(d){return u(d).next().value}),uh("data-google-av-dm"),M(Wh))}function Wh(a){return a&&a in Uh?Number(a):2};var Kh=function(a){a=a.g(Sf(new J),Ub());var b=a.g(Q(function(d){return 3!==d.rd}),Q(function(d){return void 0!==d.rb}),M(),Q(),M()),c=a.g(Q(function(d){return 3!==d.rd}),M(function(d){return d.dd instanceof R?"msf":d.Xc instanceof hd?"c":!1===d.be?"pv":d.dd||d.Xc?"x":null}),Q(function(d){return null!==d}),M());b=Kc(c,b);return P([b,
a]).g(M(),eg(),Ff())};function Xh(a){return"string"===typeof a?encodeURIComponent(a):"number"===typeof a?String(a):Array.isArray(a)?a.map(Xh).join(","):a instanceof qd?a.toString():!0===a?"1":!1===a?"0":void 0===a||null===a?null:[a.top,a.left,a.top+a.height,a.left+a.width].join()}function Yh(a){a=Object.entries(a).map(function(b){var c=u(b);b=c.next().value;c=c.next().value;c=Xh(c);return null===c?"":b+"="+c}).filter(function(b){return""!==b});return a.length?a.join("&"):""};;function Zh(a,b){return Za(a,function(c){if("string"===typeof b.Hc){var d="&"+Yh({uach:b.Hc});return"&adurl="==c.substring(c.length-7)?c.substring(0,c.length-7)+d+"&adurl=":c+d}return c})};var Ih=G(eg(function(a){return void 0===a.jc}),Q(function(a){var b=a.Hd;return!!a.jd&&!!b}),M(),eg(),Ff());function $h(){var a=ai;return G(M(function(b){var c;if(null==b)var d=void 0;else a:if(b=b.bd[a.key],"proto"===a.valueType){try{var e=JSON.parse(b);if(Array.isArray(e)){d=e;break a}}catch(f){}d=a.defaultValue}else d=typeof b===typeof a.defaultValue?b:a.defaultValue;return null!=(c=d)?c:!1}),M(function(b){return"number"===typeof b?b:null}))};function bi(a){return G(M(function(){return!0}),U(!1),W(a))};function ci(a){return 0>=a.length?Jb:P(a.map(function(b){var c=0;return b.g(M(function(d){return{index:c++,value:d}}))})).g(Q(function(b){return b.every(function(c){return c.index===b[0].index})}),M(function(b){return b.map(function(c){return c.value})}))};function di(a,b){a.Yc&&(a.Bc=a.Yc);a.Yc=b;a.Bc&&a.Bc.value?(b=Math.max(0,rd(b.timestamp,a.Bc.timestamp)),a.totalTime+=b,a.Xa+=b):a.Xa=0;return a}function ei(){return G(Pf(di,{totalTime:0,Xa:0}),M(function(a){return a.totalTime}))}function fi(){return G(Pf(di,{totalTime:0,Xa:0}),M(function(a){return a.Xa}))};function gi(a,b){return G(uh("data-google-av-metadata"),M(function(c){if(null===c)return b(void 0);c=c.split("&").map(function(d){return d.split("=")}).filter(function(d){return d[0]===a});return 0===c.length?b(void 0):b(c[0].slice(1).join("="))}))};var hi={uf:"asmreq",vf:"asmres"};var ii=function(a){De.call(this,a)};y(ii,De);ii.prototype.yd=function(a){qe(this,1,a)};var ji=function(a){De.call(this,a)};y(ji,De);ji.prototype.yd=;var ki=function(a){De.call(this,a)};y(ki,De);function li(a,b){var c=void 0===c?mh(a):c;var d=new MessageChannel;b=b.g(M(function(f){return Number(f)}),Q(function(f){return!isNaN(f)&&0!==f}),hg(function(f){var g=new ii;g.yd(f);f={type:"asmreq",payload:ve(g)};c.postMessage(f,"*",[d.port2])}),uf());var e=nh(a,d.port1).g(Q(function(f){return"object"===typeof f.data}),M(function(f){var g=f.data,h=Object.values(hi).includes(g.type);g="string"===typeof g.payload;if(!h||!g||"asmres"!==f.data.type)return null;try{var k=f.data.payload;Sa(ji);if(null==
k||""==k)var l=Xa(new ji,S);else{Ra(k);var m=JSON.parse(k);if(!Array.isArray(m))throw Error("F`"+Ba(m)+"`"+m);te=m;var t=new ji(m);te=null;Xa(t,S);l=t}return l}catch(q){return null}}),Q(function(f){return null!==f}),M(function(f){return f}));return b.g(V(function(f){return K(f).g(ff(e))}),Q(function(f){var g=u(f);f=g.next().value;g=g.next().value;return null!=pe(g,1)?re(g,1,0)===f:!1}),M(function(f){f=u(f);f.next();return f.next().value}),qg(a.h))};function mi(a,b,c){var d=b.ib.g(uf(),V(function(){return li(a,c)}),Q(function(f){var g=pe(f,2);g=null==g?g:!!g;return(null==g?!1:g)&&null!=pe(f,3)&&null!=pe(f,4)&&null!=pe(f,5)}),uf(),qg(a.h));b=d.g(M(function(f){var g=se(f,ki,3);g=re(g,2,0);f=se(f,ki,3);return{x:g,y:re(f,1,0)}}),T(),W(a.h));var e=d.g(M(function(f){return re(f,4,0)}),W(a.h));d=d.g(M(function(f){return re(f,5,0)}),W(a.h));return{xe:e,Td:b,He:d}};function ni(a,b){return b.ib.g(uf(),M(function(){return a.i.now().round()}))};function oi(a,b,c){c=void 0===c?function(d,e){return d===e}:c;return a.timestamp.equals(b.timestamp)&&c(a.value,b.value)};var pi=M(function(a){return[a.value.ka.width,a.value.ka.height]});function qi(a,b){return function(c){return ci(b.map(function(d){return c.g(a(d))}))}};function ri(){var a;return G(hg(function(b){return void(a=b.timestamp)}),fi(),M(function(b){return{timestamp:a,value:Math.round(b)}}))};var si={aa:"ns",W:Ng,ka:Ng,Z:new J,pa:"ns",V:Ng,fa:Ng};;var ui=;function vi(a,b){return };function xi(a){return function(b){return b.g(a.ResizeObserver?yi(a):zi(a),Xf(),Ub())}}function yi(a){return function(b){return b.g(V(function(c){var d=a.ResizeObserver;if(!d)return K(si.V);var e=(new I(function(f){var g=new d();g.observe(c);return })).g(Te(a.s,736),M());return Kc(K(c.getBoundingClientRect()),e)}),T(Og))}}
;function Ai(a,b){var c=Bi(a,b).g(Xf(),Ub());return function(d){d=d.g(V(function(e){return e.element}),T());return P([c,d]).g(V(function(e){var f=u(e);e=f.next().value;f=f.next().value;return Ci(a,e.Ae,xi(a),e.Re,e.qe,f)}),qg(a.h))}}function Di(a){return M(function(b){return"nio"!==b.value.aa?b:Object.assign({},b,{value:Object.assign({},b.value,{W:oh(a,!0),ka:oh(a,!0)})})})}function Ei(a,b){return K(b).g(a,M(function(){return b}))}
function Bi(a,b){return a.i.timeline!==od?Ob(new R(2)):a.MutationObserver?"undefined"===typeof IntersectionObserver?Ob(new R(0)):(new I(function(c){var d=new J,e=new IntersectionObserver(d.next.bind(d),{threshold:[].concat(w(b))});c.next({Re:d.g(Te(a.s,735)),Ae:e,qe:function(){var f=e.takeRecords();0<f.length&&d.next(f)}})})).g(uf(),Xf(),Ub()):Ob(new R(1))}function Fi(a){return xc(a.sort())}
function Ci(a,b,c,d,e,f){return new I(function(g){b.observe(f);var h=new Ib({timestamp:a.i.now(),value:Object.assign({},si,{aa:"nio",pa:"nio"})}),k=d.g(Ac(function(q){return Fi(q)}),Q(function(q){return q.target===f}),M(function(q){return{timestamp:new qd(q.time,od),value:{aa:"nio",W:q.rootBounds||Ng,ka:q.rootBounds||oh(a,!0),Z:l,pa:"nio",fa:q.intersectionRect,V:q.boundingClientRect}}}),Sf(h),Ub()).subscribe(g),l=new J,m=l.subscribe(function(){e();g.next({timestamp:a.i.now(),value:h.value.value});
b.unobserve(f);b.observe(f)}),t=Ei(c,f).subscribe(function(){l.next()});return })};function Gi(a,b){var c=a.nc().g(M());return Pc(b,c).g(uf(),W(a.h))};function Hi(a){return function(b){var c;return b.g(hg(function(d){return void(c=d.timestamp)}),M(function(d){return d.value}),a,M(function(d){return{timestamp:c,value:d}}))}};var Ii=Hi(G(M(function(a){var b;return null!=(b=a.Of)?b:a.fa.width*a.fa.height/(a.V.width*a.V.height)}),M(function(a){return isFinite(a)?a:0})));function Ji(a){var b=new R(13);if(1>a.length)return{Vc:Jb,ac:Jb};var c=new J;return{Vc:a.slice(1).reduce(function(d,e){return d.g(bf())},a[0]).g(bf(),Sf(new J),Ub()),ac:c}};function Ki(a){try{var b=a.getBoundingClientRect();return b&&30<=b.height&&30<=b.width}catch(c){return!1}}function Li(a){if(!a.children)return a;for(var b=ab(a.children);b.length;){var c=b.filter(Ki);if(1===c.length)return c[0];if(1<c.length)break;b=eb(b,)}return a}
function Mi(a,b,c,d){if(c)return{Ab:b,Da:K(null)};c=b.element.g(M(function(e){a:if(Ki(e))e={Jb:e,Da:"mue"};else{var f=Li(e);if(Ki(f))e={Jb:f,Da:"ie"};else{if(d||a.pc)if(f=a.document.querySelector(".GoogleActiveViewInnerContainer")){e={Jb:f,Da:"ce"};break a}e={Jb:e,Da:"mue"}}}return e}),Zf());return{Ab:{$a:b.$a,element:c.g(M(function(e){return e.Jb}))},Da:c.g(M(function(e){return e.Da}))}};function Ni(a){return function(b){return b.g(kg(a),M(function(c){var d=u(c);c=d.next().value;d=d.next().value;var e=c.value;return{timestamp:c.timestamp,value:1<=e?!0:0>=e?!1:e>=d}}))}};var Oi=M(function(a){return"geo"===a.value.pa?a.value.aa:a.value.pa});var Pi=Hi(G(M(),M()));function Qi(a,b,c){return a?P([b,c]).g(Q(),M()):b}function Ri(a){return function(b){var c=b.g(Ii),d=b.g(Pi);return a instanceof I?a.g(V(function(e){return Qi(e,c,d)})):Qi(a.value,c,d)}};function Si(a,b,c,d){var e=d.ed,f=d.$c,g=d.rf,h=d.Ud,k=d.pd,l=d.Ke;d=d.ld;b=Ti(a,c,b);c=Ui(a,c);var m=Vi(a,e,l,b),t=m.g(M(function(x){return x.value}),T(),W(a),Pf(function(x,B){return Math.max(x,B)},0));g=Wi(a,b,g,h);var q=g.g(U(!1),T(),M(function(x){return x?k:f}));h=m.g(Ni(q),T(),W(a));var H=P([h,b]).g(Q(function(x){var B=u(x);x=B.next().value;B=B.next().value;return x.timestamp===B.timestamp}),M(function(x){var B=u(x);x=B.next().value;B=B.next().value;return{visible:x.value,geometry:B.value.V}}),
Pf(function(x,B){return!B.visible&&x.visible?x:B},{visible:!1,geometry:Ng}),M(function(x){return x.geometry}),U(Ng),W(a),T(Og));l=l instanceof I?l.g(T(),Mf()):Mc;q=P([l,q]).g(Mf());var F=b.g(Q(function(x){return"ns"!==x.value.aa&&"ns"!==x.value.pa}),Pf(function(x){return x+1},0),U(0),W(a)),v=c.g(Mf(!0),U(!1),W(a));a=P([d,v]).g(M(function(x){var B=u(x);x=B.next().value;B=B.next().value;return x&&!B}),W(a));return{ff:l,gf:q,se:{$f:b,Le:b.g(Oi),hc:H.g(T(Og)),visible:h.g(T(oi)),qf:m.g(T(oi)),Je:t,Zd:b.g(pi,
T(bb)),dd:c,Z:b.g(M(function(x){return x.value.Z})),Fe:g,ed:e,ld:d,fd:a,eg:F}}}function Ui(a,b){return b.g(Q(function(){return!1}),M(),bf())}function Ti(a,b,c){return b.g(Tf(Mc),W(a)).g(T(function(d,e){return oi(d,e,ti)}),U({timestamp:c.now(),value:si}),W(a))}
function Vi(a,b,c,d){c=d.g(Ri(c),Hi(M(function(e){var f=Math.pow(10,2);return Math.round(e*f)/f})),W(a));return b instanceof X?c:P([c,b]).g(M(function(e){var f=u(e);e=f.next().value;f=f.next().value;return{timestamp:f.timestamp.maximum(e.timestamp),value:f.value?0:e.value}}),T(oi),W(a))}
function Wi(a,b,c,d){b=[b.g(M())];c instanceof I&&b.push(c.g(M()));c=P(b);return d?c.g(M(),U(!1),T(),W(a)):(new X(!1)).ya(a)};var Xi=G(uh("data-google-av-itpl"),M(function(a){return Number(a)}),M(function(a){return isNaN(a)?1:a}));var Yi={tf:"addEventListener",zf:"getMaxSize",Af:"getScreenSize",Bf:"getState",Cf:"getVersion",Ef:"removeEventListener",Df:"isViewable"},$i=function(a,b){b=void 0===b?:b;this.T=null;this.ze=new J;var c=a.pc,d=!a.Oa;if(c&&d){var e=a.global.top.mraid;if(e){this.yb=b(e);this.T=e;this.Ea=3;return}}(a=a.global.mraid)?(this.yb=b(a),this.T=a,this.Ea=c?d?2:1:0):(this.Ea=-1,this.yb=2)};$i.prototype.addEventListener=;
$i.prototype.removeEventListener=;$i.prototype.gd=;$i.prototype.getState=;
var aj=,bj=,Zi=;$i.prototype.Ra=;
p.Object.defineProperties($i.prototype,{Zc:{configurable:!0,enumerable:!0,get:,set:}});function cj(a,b){return-1!==(new $i(a)).Ea?(new X(!0)).ya(a.h):b.g(uh("data-google-av-inapp"),M(function(c){return null!==c}),W(a.h))};var ej=function(a,b){var c=this;this.context=a;this.vc=this.Ib=null;this.$e=b.g(T()).subscribe(function(d){dj(c);c.vc=d})},fj=,dj=function(a){null!==a.Ib&&a.context.i.clearTimeout(a.Ib);a.Ib=null};function gj(a,b,c,d,e){var f=hj.nf;var g=void 0===g?new ej(a,d):g;return(new I(function(h){var k=c.g(U(void 0),V(function(){return ij(e)})).g(M(function(l){var m=l.value;l=l.timestamp;var t=m.visible;m=m.zb;var q=m>=f;q||!t?dj(g):(l=Math.max(0,rd(b.now(),l)),fj(g,Math.max(0,f-m-l)));return q}),Pf(function(l,m){return m||l},!1),T()).subscribe(h);return })).g(eg(function(h){return!h},!0),W(a.h))}
function ij(a){return ci([a,a.g(ri())]).g(M(function(b){var c=u(b);b=c.next().value;c=c.next().value;return{timestamp:b.timestamp,value:{visible:b.value,zb:c.value}}}),T(function(b,c){return oi(b,c,)}))};function jj(a,b){return{Zb:b.g(uh("data-google-av-adk")),$b:b.g(uh("data-google-av-btr"),T(),M(function(c){return null===c?[]:c.split("|").filter(function(d){return""!==d})})),dc:b.g(uh("data-google-av-cpmav"),T(),M(function(c){return null===c?[]:c.split("|").filter(function(d){return""!==d})})),ee:Vh(a,b),flags:b.g(uh("data-google-av-flags"),T()),qa:cj(a,b),tc:b.g(gi("cr",function(c){return"1"===c}),T()),rc:b.g(Xi),metadata:b.g(uh("data-google-av-metadata")),va:b.g(Bh),ma:b.g(vh),sf:b.g(gi("la",
),T())}};function kj(){return G(fi(),Pf(function(a,b){return Math.max(a,b)},0),M(function(a){return Math.round(a)}))};function lj(a){return G(Ni(K(a)),kj())};function mj(a,b,c,d,e){c=c.g(M(function(){return!1}));d=P([e,d]).g(V(function(f){f=u(f).next().value;return nj(b,f)}));return Kc(K(!1),c,d).g(T(),W(a.h))}function nj(a,b){return a.g(M(function(c){return b||0===c||2===c}))};var oj=[33,32],pj=G(Xi,M(function(a){return 0<=oj.indexOf(a)}),T());function qj(a,b,c,d,e){var f=c.g(M(function(h){return 9===h})),g=b.element.g(pj);c=e.g(Q(function(h){return h}),V(function(){return P([f,g])}),M(function(h){h=u(h);var k=h.next().value;return!h.next().value||k}),T());c=P([c,d.g(T())]).g(M(function(h){var k=u(h);h=k.next().value;k=k.next().value;return Mi(a,b,!h,k)}),Xf(),Ub());d=c.g(M(function(h){return h.Ab}));c=c.g(V(function(h){return h.Da}),U(null),T(),W(a.h));return{Ba:d,Ya:c}};function rj(a){var b=void 0===b?!1:b;return G(V(function(c){return Mg(a.document,c,b)}),W(a.h))};var sj=function(a,b,c,d,e){this.ib=b.element.g(rj(a),W(a.h));this.Ad=mj(a,c,b.element,this.ib,d);c=qj(a,b,e,d,this.Ad);d=c.Ya;this.Ba=c.Ba;this.Ya=d;this.Kc=Kc((new X(1)).ya(a.h),b.element.g(uf(),M(function(){return 2})),this.ib.g(uf(),M(function(){return 3})),this.Ad.g(Q(Boolean),uf(),M(function(){return 0}))).g(eg(function(f){return 0!==f},!0),W(a.h))};function tj(a,b){return a&&0===b?15:a||1!==b?null:14}function uj(a,b,c){return b instanceof I?b.g(V(function(d){return(d=tj(d,c))?Ob(new R(d)):a})):(b=tj(b.value,c))?Ob(new R(b)):a};var vj=;var wj=function(a,b){this.context=a;this.lf=b};y(wj,vj);wj.prototype.Ja=function(a,b){var c=this.lf.map(function(f){return f.Ja(a,b)}),d=Ji(c.map(function(f){return f.Na})),e=d.ac.g(xj());return{Na:d.Vc.g(W(this.context.h)),Ia:Object.assign.apply(Object,[{Fc:e,dg:d.ac}].concat(w(c.map(function(f){return f.Ia}))))}};var xj=function(){return Pf(,[])};function yj(a,b){var c=a.g(Sf(new J),Ub());return V()};function zj(a,b){var c=void 0===c?:c;var d=a.Oa?Lg(a.document)?a.Ee?null:Ob(new R(5)):Ob(new R(4)):Ob(new R(3));if(d)return d;var e=new J;return Kc(K({}),b,e).g(M(),W(a.h))}

;var Cj=function(a,b){this.context=a;this.lb=b};y(Cj,vj);Cj.prototype.Ja=function(a,b){var c=yj(zj(this.context,this.lb),vi(this.context,b.va));return{Na:uj(a.Ba.g(c),b.qa,0),Ia:{}}};function Dj(a,b){if(a.Oa)return Ob(new R(6));var c=new J;return Kc(K({}),b,c).g(M(),qg(a.h))};var Fj=function(a,b){this.context=a;this.lb=b};y(Fj,vj);Fj.prototype.Ja=function(a,b){var c=yj(Dj(this.context,this.lb),vi(this.context,b.va));return{Na:uj(a.Ba.g(c),b.qa,0),Ia:{}}};var Gj=function(a,b,c){c=void 0===c?Ai(a,b):c;this.context=a;this.Be=c};y(Gj,vj);Gj.prototype.Ja=function(a,b){return{Na:uj(a.Ba.g(this.Be,Di(this.context)),b.qa,0),Ia:{}}};function Hj(a,b,c,d,e){var f=void 0===f?new $i(a):f;var g=void 0===g?af(a.i,500):g;var h=void 0===h?af(a.i,100):h;e=K(f).g(Ij(c),hg(),Jj(a,h),Kj(a),Lj(a,e),Xf(),Ub());f=new J;b=Kc(K({}),b,f);return e.g(Mj(a,f,b,g,c),W(a.h))}
function Lj(a,b){return G(function(c){return P([c,b])},kf(),M())}function Ij(a){return V()}
function Jj(a,b){return kf()}var Kj=function(a){return V()};
function Mj(a,b,c,d,e){return V()}


;var Qj=function(a,b){this.context=a;this.lb=b};y(Qj,vj);Qj.prototype.Ja=function(a,b){var c=new Qb(1),d=new Qb(1),e=yj(Hj(this.context,this.lb,c,d,b.va),vi(this.context,b.va));return{Na:uj(a.Ba.g(e),b.qa,1),Ia:{wc:c.g(W(this.context.h)),xc:d.g(W(this.context.h))}}};function Rj(a){return a.document.Xe.g(M(function(b){return"visible"===b}),T(),W(a.h))};var Sj=function(){this.bd={}};var Tj=function(a){var b=new Sj;return G(M(function(c){if(null===c)return null;try{var d=JSON.parse(c)[0];c="";for(var e=0;e<d.length;e++)c+=String.fromCharCode(d.charCodeAt(e)^"\u0003\u0007\u0003\u0007\b\u0004\u0004\u0006\u0005\u0003".charCodeAt(e%10));b.bd=JSON.parse(c)}catch(f){}return b}),W(a.h))};var Uj;Uj=["av.key","js","20220504"].slice(-1)[0];function Vj(a,b,c){var d;return b.g(T(),V(function(e){return c.g(M())}),U(!1),W(a.h))};function Wj(a){return G(Hi(M(function(b){return 1<=b?!0:0>=b?!1:b>=a})),ei(),M(function(b){return Math.round(b)}))};function Xj(a,b,c,d,e){var f=Yj;if(1<f.length)for(var g=0;g<f.length-1;g++)if(f[g]<f[g+1])throw Error();g=e.g(U(void 0),V(function(){return c.g(ri())}),T(),W(a));e=e.g(U(void 0),V(function(){return c.g(kj())}),T(),W(a));return{qd:d.g(U(void 0),V(function(){return b.g(qi(lj,f))}),T(bb),W(a)),Dd:d.g(U(void 0),V(function(){return b.g(qi(Wj,f),M(function(h){return h.map(function(k,l){return 0<l?k-h[l-1]:k})}))}),T(bb),W(a)),Ie:e,zb:g.g(T(oi),W(a))}};function Zj(a,b,c){var d=c.g(M(function(e){return{value:e,timestamp:a.i.now()}}),T(oi));return b instanceof I?b.g(T(),V(function(e){return e?(new X({value:!1,timestamp:a.i.now()})).ya(a.h):d})):!1===b.value?d:new X(!1)}function ak(a,b,c,d,e,f){var g=hj;b=b instanceof I?b.g(U(!1),T()):b;var h=!(Ne()||Oe());c=Zj(a,c,d);a=f.Ba.g(bi(a.h));return Object.assign({},g,{ed:c,rf:e,Ud:h,Ke:b,ld:a})};function bk(a){a=a.global;if("undefined"===typeof a.__google_lidar_)return a.__google_lidar_=1,!1;a.__google_lidar_=Number(a.__google_lidar_)+1;var b=a.__google_lidar_adblocks_count_;if("number"===typeof b&&0<b&&(a=a.__google_lidar_radf_,"function"===typeof a))try{a()}catch(c){}return!0}
function ck(a){var b=a.global;b.osdlfm=function(){return b.__google_lidar_radf_};if(void 0!==b.__google_lidar_radf_)return Jb;b.__google_lidar_adblocks_count_=1;var c=new J;b.__google_lidar_radf_=;return c.g(Te(a.s,743))};var ai=new function(a,b){this.key=a;this.defaultValue=void 0===b?0:b;this.valueType="number"}("45362137");var hj=Object.freeze({nf:1E3,$c:.5,pd:.3}),Yj=Object.freeze([1,.75,hj.$c,hj.pd,0]),Oh="https://pagead2.googlesyndication.com/pagead/gen_204?id=av-js&type=error&bin=7&v="+Uj;
function dk(a,b,c,d){var e=bk(a),f=ck(a);f=Ch(a,f);e=e?Jb:f.g(M(function(k){return Object.freeze({$a:lb(),element:(new X(k)).ya(a.h)})}),wh());var g=Rj(a).g(M(function(k){return!k})),h=new wj(a,[new Gj(a,Yj),new Fj(a,d),new Cj(a,d),new Qj(a,d)]);return Fh(a,e,function(k,l){var m=jj(k,l.element),t=m.Zb,q=m.$b,H=m.dc,F=m.ee,v=m.qa,x=m.rc,B=m.tc,la=m.va,fc=m.ma,ma=m.sf;m=m.flags.g(T(),Tj(k));var xb=new sj(k,l,F,v,la),Tc=h.Ja(xb,{qa:v,va:la}),db=Tc.Na,kc=Tc.Ia;Tc=kc.wc;var ek=kc.xc;kc=kc.Fc;ma=ak(k,B,
v,g,ma,xb);db=Si(k.h,k.i,db,ma);ma=db.se;var Uc=db.gf;db=Xj(k.h,ma.qf,ma.visible,db.ff,Uc);Uc={Hd:gj(k,k.i,Uc,ma.Z,ma.visible)};var Vc=Gi(k,c.g(Mf("t"))),fk=Vj(k,ma.Z,Vc.g(Q())),xg=gk(k,xb,t),ik=hk(k,Vc,l.element),jk=xg.Td.g(U({x:0,y:0}));return Object.assign({},{I:new X(k.I),Eb:new X("lidar2"),Ed:new X("lidartos"),Yd:new X(Uj),Xd:new X(7),Xc:new X(k.validate()?null:new hd),be:new X(Kg(k.document)),R:new X(Qh),jc:Vc,rb:Vc,ag:fk,jd:sg,de:new X(k.Oa?1:void 0),fe:new X(k.$d?
1:void 0),qa:v,wc:Tc.g(W(k.h)),xc:ek.g(W(k.h)),oe:m.g($h()),ce:l.element.g(M(function(Ia){return null!==Ia})),Db:fc,Fd:fc,dc:H.g(U([])),ue:H.g(M(function(Ia){return 0<Ia.length?!0:null}),U(null),T()),$b:q.g(U([]),W(k.h)),Xf:m,Zb:t,Ya:xb.Ya,rc:x.g(U(0),W(k.h)),rd:F,va:la.g(U(0),W(k.h)),Ta:new X(Ph),Jc:new X(Zh),tc:B,Ce:xb.ib.g(bi(k.h)),Kc:xb.Kc},ma,{hc:P([ma.hc,jk]).g(M(function(Ia){var Wc=u(Ia);Ia=Wc.next().value;Wc=Wc.next().value;return Qg(Ia,Wc)}),T(Og))},db,xg,Uc,{Hc:tg(k),ve:ik,Fc:kc})},Nh(a,
b))}function gk(a,b,c){var d=void 0===d?Aa:d;var e,f;d=(null==(e=d.performance)?void 0:null==(f=e.timing)?void 0:f.navigationStart)||0;return Object.assign({},{Sd:new X(d),Rd:ni(a,b)},mi(a,b,c))}function hk(a,b,c){return b.g(Q(),V(),M(),M())};(function(a,b,c,d){b=void 0===b?.01:b;c=void 0===c?af(a.i,36E5):c;d=void 0===d?a.i.interval(100).g(W(a.h)):d;return a.s.ja(742,function(){return dk(a,b,c,d)})()})(new lh).subscribe();}).call(this);
