(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var l="function"==typeof Object.defineProperties?Object.defineProperty:;
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var n=ba(this),p="function"===typeof Symbol&&"symbol"===typeof Symbol("x"),r={},u={};function w(a,b){var c=u[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]}
function x(a,b,c){if(b)a:{var d=a.split(".");a=1===d.length;var g=d[0],h;!a&&g in r?h=r:h=n;for(g=0;g<d.length-1;g++){var e=d[g];if(!(e in h))break a;h=h[e]}d=d[d.length-1];c=p&&"es6"===c?h[d]:null;b=b(c);null!=b&&(a?l(r,d,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===u[d]&&(a=1E9*Math.random()>>>0,u[d]=p?n.Symbol(d):"$jscp$"+a+"$"+d),l(h,u[d],{configurable:!0,writable:!0,value:b})))}}
x("Symbol",function(a){if(a)return a;c.prototype.toString=;var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",g=0;return b},"es6");
x("Symbol.iterator",function(a){if(a)return a;a=(0,r.Symbol)("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=n[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&l(d.prototype,a,{configurable:!0,writable:!0,value:})}return a},"es6");
var ea="function"==typeof Object.create?Object.create:,y;
if(p&&"function"==typeof Object.setPrototypeOf)y=Object.setPrototypeOf;else{var z;a:{var fa={a:!0},ha={};try{ha.__proto__=fa;z=ha.a;break a}catch(a){}z=!1}y=z?:null}var ia=y;
function A(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.U=b.prototype}function B(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.A=this.s=0;this.j=null}function C(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}B.prototype.o=function(a){this.i=a};
B.prototype.return=function(a){this.j={return:a};this.g=this.A};function E(a,b,c){a.g=c;return{value:b}}function ja(a){this.g=new B;this.h=a}
function G(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,D(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.P)throw b.O;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function la(a){this.next=function(b){C(a.g);a.g.h?b=F(a,a.g.h.next,b,a.g.o):(a.g.o(b),b=G(a));return b};this.throw=;this.return=;this[w(r.Symbol,"iterator")]=}function ma(a){function b(d){return a.next(d)}return new r.Promise(function(d,g){function h(e){e.done?d(e.value):r.Promise.resolve(e.value).then(b,c).then(h,g)}h(a.next())})}
function H(a){return ma(new la(new ja(a)))}
x("Promise",function(a){if(a)return a;c.prototype.h=;var g=n.setTimeout;c.prototype.i=;c.prototype.l=;c.prototype.j=;b.prototype.j=;b.prototype.K=;
b.prototype.J=;b.prototype.l=;b.prototype.o=;b.prototype.A=;b.prototype.L=;b.prototype.S=
;b.prototype.R=;var h=new c;b.prototype.M=
;b.prototype.N=;b.prototype.then=;b.prototype.catch=;b.prototype.B=;b.resolve=d;b.reject=;b.race=;b.all=;return b},"es6");
x("Array.from",function(a){return a?a:},"es6");
x("Promise.allSettled",function(a){function b(d){return{status:"fulfilled",value:d}}return a?a:function(d){var g=this;d=w(Array,"from").call(Array,d,function(h){return g.resolve(h).then(b,c)});return g.all(d)}},"es_2020");var I=this||self;function J(a){return a};function K(a,b){this.h=a===L&&b||"";this.g=na}function M(a){return a instanceof K&&a.constructor===K&&a.g===na?a.h:"type_error:Const"}var na={},L={};var N;function O(a,b){this.g=b===oa?a:""}O.prototype.toString=;function pa(a){return a instanceof O&&a.constructor===O?a.g:"type_error:TrustedResourceUrl"}
var sa=/%{(\w+)}/g,ra=RegExp("^((https:)?//[0-9a-z.:[\\]-]+/|/[^/\\\\]|[^:/\\\\%]+/|[^:/\\\\%]*[?#]|about:blank#)","i"),oa={};
function S(a){if(void 0===N){var b=null;var c=I.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:J,createScript:J,createScriptURL:J})}catch(d){I.console&&I.console.error(d.message)}N=b}else N=b}a=(b=N)?b.createScriptURL(a):a;return new O(a,oa)};/*

 SPDX-License-Identifier: Apache-2.0
*/
;function T(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)};
function va(a,b){var c=window;return new r.Promise(function(d){void 0===b&&(b=c.document.createElement("iframe"));b.addEventListener("load",function(){d(b)});b.src=pa(a).toString();b.width="0";b.height="0";b.style.display="none";c.document.body.appendChild(b)})};function xa(a){a=void 0===a?document:a;return a.createElement("img")};
U.prototype.snapshotSync=;
;function Ca(a){switch(a){case "pt":case "cr":return a;default:return""}}function Da(a){switch(a){case "env":case "int":return a;default:return"env"}}function Ea(){var a=window.GoogleGcLKhOms;if(a&&0<a.length&&(a=a.shift()))return void 0===a._rc_?{context:Ca(a._ctx_),v:a._bgv_,u:a._bgp_,F:a._li_,D:a._jk_,G:Da(a._st_),m:a._dl_,C:a._g2_}:{context:Ca(a._ctx_),v:a._bgv_,u:a._bgp_,F:a._li_,D:a._jk_,G:Da(a._st_),H:a._rc_,m:a._dl_,C:a._g2_}}
;function Ha(a){this.g=a;var b=this;this.h=!1;var c=new MessageChannel;this.port=c.port1;this.i=new r.Promise(function(d){b.port.onmessage=function(){d()};b.g.postMessage("GoogleBasRYoCJlVEB","https://tpc.googlesyndication.com",[c.port2])})}A(Ha,V);
function Ia(a,b){return H(function(c){return 1==c.g?E(c,a.i,2):c.return(new r.Promise(function(d,g){var h=new MessageChannel;h.port1.onmessage=function(e){h.port1.close();Array.isArray(e.data)?d(e.data):g(9)};a.port.postMessage(b,[h.port2])}))})}function Ja(a,b){var c;return H(function(d){if(1==d.g)return d.s=2,E(d,Ia(a,[1,b.T,b.I,b.m]),4);if(2!=d.g)return c=d.i,d.return({response:c[0],error:c[1]});d.s=0;d.j=null;return d.return({error:9})})}A(Ka,V);function La(a,b){Ma(a,void 0===b?null:b)}function Ma(a,b){var c=window;c.google_image_requests||(c.google_image_requests=[]);var d=xa(c.document);if(b){var g=function(h){b&&b(h);d.removeEventListener&&d.removeEventListener("load",g,!1);d.removeEventListener&&d.removeEventListener("error",g,!1)};T(d,"load",g);T(d,"error",g)}d.src=a;c.google_image_requests.push(d)};function Na(){this.url="https://pagead2.googlesyndication.com/pagead/gen_204?id=sodar2&v=225"}function W(a,b,c){a.url+="&"+b+"="+encodeURIComponent(c.toString())}function X(a,b,c){var d=new Na,g=void 0===b||"0"!==b.C;!1!==c&&g||(d.url="https://pagead2.googlesyndication.com/pagead/sodar?id=sodar2&v=225");W(d,"t",a);b&&(W(d,"li",b.F),W(d,"cr"===b.context?"bgai":"jk",b.D));return d}function Y(a){return new r.Promise(function(b){La(a,function(){b()})})}
;function Pa(){var a=this;this.promise=new r.Promise(function(b,c){a.resolve=b;a.reject=c})};function Z(a){this.g=a;this.m=0;this.m=Number(this.g.m)||0}Z.prototype.snapshotSync=;
function Sa(a){var b;return H(function(c){if(1==c.g){b=a;if(Ra(a))var d=Ta(a);else a.h=new U(a.g.v,a.g.u,a.m),d=ya(a.h);return E(c,d,2)}b.l=c.i;if(a.l){d=a.g;var g=a.l,h=X(2,d,void 0!==g);void 0!==g&&W(h,"bg",g);d=2E3<h.url.length?Oa(4,d):Y(h.url);c=E(c,d,0)}else c.g=0,c=void 0;return c})}
function Ua(a,b){function c(h){h&&null!==h.data&&"https://www.google.com"===h.origin&&null!=h.source&&h.source===b.contentWindow&&(a.i="id=sodar2&v=225",a.g&&(a.i+="&li="+encodeURIComponent(a.g.F.toString()),a.i+="&"+("cr"===a.g.context?"bgai":"jk")+"="+encodeURIComponent(a.g.D.toString()),h.source.postMessage(JSON.stringify({id:"sodar",params:a.i}),"https://www.google.com"),d.removeEventListener("message",c,!1)),g.resolve())}var d=window,g=new Pa;d.addEventListener("message",c,!1);return g.promise}
function Va(a){var b,c,d,g,h;return H(function(e){if(1==e.g){if("y"!==a.g.H)return e.return();b=S(M(new K(L,"https://www.google.com/recaptcha/api2/aframe")));c=window.document.createElement("iframe");d=va(b,c);g=Ua(a,c);return E(e,r.Promise.all([d,g]),2)}h=e.i;if(null===h[0].contentWindow)throw 15;e.g=0})}function Wa(a){return H(function(b){return E(b,w(r.Promise,"allSettled").call(r.Promise,[Sa(a),Va(a)]),0)})}
function Ra(a){return"tpc.googlesyndication.com"===window.location.host||"int"===a.g.G?!1:!0}
function Ta(a){var b,c,d;return H(function(g){if(1==g.g)return b=S(M(new K(L,"https://tpc.googlesyndication.com/sodar/sodar2/225/runner.html"))),E(g,va(b),2);if(4!=g.g){c=g.i;if(!c.contentWindow)throw 3;var h=c.contentWindow;h=window.hasOwnProperty("MessageChannel")?new Ha(h):new Ka(h);a.j=h;if(a.j.h){h=a.j.g;var e=h.postMessage;var f=a.g;f=JSON.stringify([f.context,f.v,f.u,f.F,f.D,f.G,void 0===f.H?"n":f.H,void 0===f.m?"0":f.m,void 0===f.C?"1":f.C]);e.call(h,f,"https://tpc.googlesyndication.com");
return g.return(void 0)}return E(g,Ja(a.j,{T:a.g.v,I:a.g.u,m:a.m}),4)}d=g.i;c.parentNode&&c.parentNode.removeChild(c);if(d.error)throw d.error;return g.return(d.response)})};A(Xa,Z);Xa.prototype.o=;function Ya(){Z.apply(this,arguments)}A(Ya,Z);Ya.prototype.o=function(){var a=this;return H(function(b){return E(b,Wa(a),0)})};
function $a(a){switch(a.context){case "pt":a=new Ya(a);break;case "cr":a=new Xa(a);break;default:throw 2;}if(!window.postMessage&&Ra(a))throw 8;return a.o()};(function(){var a=Ea();try{return a?$a(a):r.Promise.race([Fa(),new r.Promise()]).then(,)}catch(b){return Za(b,a)}})();}).call(this);
