(function(){var l,aa="function"==typeof Object.defineProperties?Object.defineProperty:,m="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ba=function(){ba=;m.Symbol||(m.Symbol=ca)},ca=function(){var a=0;return }(),p=function(){ba();var a=m.Symbol.iterator;a||(a=m.Symbol.iterator=m.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&
aa(Array.prototype,a,{configurable:!0,writable:!0,value:});p=function(){}},da=,ea=,q=function(a){p();var b=a[Symbol.iterator];return b?b.call(a):da(a)},ha="function"==typeof Object.create?Object.create:,ia;
if("function"==typeof Object.setPrototypeOf)ia=Object.setPrototypeOf;else{var ja;a:{var ka={Ca:!0},la={};try{la.__proto__=ka;ja=la.Ca;break a}catch(a){}ja=!1}ia=ja?:null}
var ma=ia,na=function(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(ma)ma(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.na=b.prototype},oa=,pa=function(a,b){if(b){var c=m;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&
aa(c,a,{configurable:!0,writable:!0,value:b})}},r=;
pa("WeakMap",function(a){if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d["delete"](b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(n){return!1}}())return a;var d="$jscomp_hidden_"+Math.random();c("freeze");c("preventExtensions");c("seal");var e=0,f=;f.prototype.set=;f.prototype.get=;f.prototype.has=;f.prototype["delete"]=;return f});
pa("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(q([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(t){return!1}}())return a;ba();p();var b=new WeakMap,c=;c.prototype.set=;c.prototype["delete"]=;c.prototype.clear=;c.prototype.has=;c.prototype.get=;c.prototype.entries=;c.prototype.keys=;c.prototype.values=;c.prototype.forEach=;c.prototype[Symbol.iterator]=c.prototype.entries;var d=,e=,f=,g=0;return c});pa("Number.isFinite",function(a){return a?a:});pa("Number.isInteger",function(a){return a?a:});var u=this,v=function(a){return"string"==typeof a},w=function(a){return"number"==typeof a},x=,qa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==
c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},z=,A=function(a){return"function"==qa(a)},ra=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},sa=function(a,b,c){return a.call.apply(a.bind,arguments)},ta=,ua=function(a,b,c){ua=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?sa:ta;return ua.apply(null,arguments)},va=Date.now||,wa=function(a,b){function c(){}c.prototype=b.prototype;a.na=b.prototype;a.prototype=
new c;a.prototype.constructor=a;a.Va=};var C=;wa(C,Error);C.prototype.name="CustomError";var xa=Array.prototype.indexOf?:,za=Array.prototype.forEach?:,Ca=function(a){var b=document;b=Aa(b.querySelectorAll&&b.querySelector?b.querySelectorAll(".GoogleActiveViewClass"):
Ba());a:{for(var c=b.length,d=v(b)?b.split(""):b,e=0;e<c;e++)if(e in d&&a.call(void 0,d[e],e,b)){a=e;break a}a=-1}return 0>a?null:v(b)?b.charAt(a):b[a]},Da=,Ea=,Aa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Fa=String.prototype.trim?:,Ga=,Ha=,Ia=;var D;a:{var Ja=u.navigator;if(Ja){var Ka=Ja.userAgent;if(Ka){D=Ka;break a}}D=""}var E=function(a){return-1!=D.indexOf(a)};var La=;var Ma=;Ma[" "]=x;var Na=;var Oa=E("Opera"),F=E("Trident")||E("MSIE"),Pa=E("Edge"),Qa=E("Gecko")&&!(-1!=D.toLowerCase().indexOf("webkit")&&!E("Edge"))&&!(E("Trident")||E("MSIE"))&&!E("Edge"),Ra=-1!=D.toLowerCase().indexOf("webkit")&&!E("Edge"),Sa=,Ta;
a:{var Ua="",Va=function(){var a=D;if(Qa)return/rv:([^\);]+)(\)|;)/.exec(a);if(Pa)return/Edge\/([\d\.]+)/.exec(a);if(F)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ra)return/WebKit\/(\S+)/.exec(a);if(Oa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Va&&(Ua=Va?Va[1]:"");if(F){var Wa=Sa();if(null!=Wa&&Wa>parseFloat(Ua)){Ta=String(Wa);break a}}Ta=Ua}var Xa=Ta,Ya={},Za;var $a=u.document;Za=$a&&F?Sa()||("CSS1Compat"==$a.compatMode?parseInt(Xa,10):5):void 0;var Ba=,bb=;var cb=function(a,b){this.Ma=100;this.Ea=a;this.Qa=b;this.aa=0;this.g=null};cb.prototype.get=function(){if(0<this.aa){this.aa--;var a=this.g;this.g=a.next;a.next=null}else a=this.Ea();return a};cb.prototype.put=function(a){this.Qa(a);this.aa<this.Ma&&(this.aa++,a.next=this.g,this.g=a)};var db=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};var eb=,fb,gb=;var hb=function(){this.fa=this.O=null},jb=new cb(function(){return new ib},function(a){a.reset()});hb.prototype.add=function(a,b){var c=jb.get();c.set(a,b);this.fa?this.fa.next=c:this.O=c;this.fa=c};hb.prototype.remove=function(){var a=null;this.O&&(a=this.O,this.O=this.O.next,this.O||(this.fa=null),a.next=null);return a};var ib=function(){this.next=this.scope=this.ja=null};ib.prototype.set=function(a,b){this.ja=a;this.scope=b;this.next=null};
ib.prototype.reset=function(){this.next=this.scope=this.ja=null};var ob=function(a,b){kb||lb();mb||(kb(),mb=!0);nb.add(a,b)},kb,lb=function(){if(u.Promise&&u.Promise.resolve){var a=u.Promise.resolve(void 0);kb=function(){a.then(pb)}}else kb=},mb=!1,nb=new hb,pb=function(){for(var a;a=nb.remove();){try{a.ja.call(a.scope)}catch(b){eb(b)}jb.put(a)}mb=!1};var H=function(a){this.u=0;this.wa=void 0;this.K=this.A=this.H=null;this.$=this.ia=!1;if(a!=x)try{var b=this;a.call(void 0,function(a){G(b,2,a)},)}catch(c){G(this,3,c)}},qb=function(){this.next=this.context=this.M=this.V=this.D=null;this.Z=!1};qb.prototype.reset=function(){this.context=this.M=this.V=this.D=null;this.Z=!1};var rb=new cb(function(){return new qb},function(a){a.reset()}),sb=function(a,b,c){var d=rb.get();d.V=a;d.M=b;d.context=c;return d};
H.prototype.then=function(a,b,c){return tb(this,A(a)?a:null,A(b)?b:null,c)};H.prototype.then=H.prototype.then;H.prototype.$goog_Thenable=!0;H.prototype.cancel=;
var ub=,yb=function(a,b){a.A||2!=a.u&&3!=a.u||xb(a);a.K?a.K.next=b:a.A=b;a.K=b},tb=function(a,b,c,d){var e=sb(null,null,null);e.D=new H(function(a,g){e.V=b?function(c){try{var e=b.call(d,c);a(e)}catch(n){g(n)}}:a;e.M=c?:g});e.D.H=a;yb(a,e);return e.D};H.prototype.Ta=;H.prototype.Ua=;
var G=function(a,b,c){if(0==a.u){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.u=1;a:{var d=c,e=a.Ta,f=a.Ua;if(d instanceof H){yb(d,sb(e||x,f||null,a));var g=!0}else{if(d)try{var h=!!d.$goog_Thenable}catch(n){h=!1}else h=!1;if(h)d.then(e,f,a),g=!0;else{if(ra(d))try{var k=d.then;if(A(k)){zb(d,k,e,f,a);g=!0;break a}}catch(n){f.call(a,n);g=!0;break a}g=!1}}}g||(a.wa=c,a.u=b,a.H=null,xb(a),3!=b||c instanceof I||Ab(a,c))}},zb=,xb=function(a){a.ia||(a.ia=!0,ob(a.Ia,a))},vb=function(a){var b=null;a.A&&(b=a.A,a.A=b.next,b.next=null);a.A||(a.K=null);return b};H.prototype.Ia=function(){for(var a;a=vb(this);)wb(this,a,this.u,this.wa);this.ia=!1};
var wb=function(a,b,c,d){if(3==c&&b.M&&!b.Z)for(;a&&a.$;a=a.H)a.$=!1;if(b.D)b.D.H=null,Bb(b,c,d);else try{b.Z?b.V.call(b.context):Bb(b,c,d)}catch(e){Cb.call(null,e)}rb.put(b)},Bb=function(a,b,c){2==b?a.V.call(a.context,c):a.M&&a.M.call(a.context,c)},Ab=,Cb=eb,I=;wa(I,C);I.prototype.name="cancel";var Db=function(a,b,c){this.Oa=a;this.resolve=b;this.reject=c};var J="StopIteration"in u?u.StopIteration:{message:"StopIteration",stack:""},K=;K.prototype.next=;K.prototype.ga=;
var Eb=,Fb=,Gb=,Hb=;var L=;l=L.prototype;l.v=;l.B=;l.R=;l.clear=;
l.remove=;var Ib=;l=L.prototype;l.get=;l.set=;
l.addAll=;l.forEach=;l.clone=;l.ga=;
var M=;var Jb=,Kb=;var Lb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Mb=;var N=;N.prototype.toString=;
N.prototype.resolve=;N.prototype.clone=;
var Nb=,Ob=,Pb=,Q=;N.prototype.removeParameter=;var O=;
N.prototype.ma=;
var Qb=,Rb=,Xb=,Sb=/[#\/\?@]/g,Ub=/[#\?:]/g,Tb=/[#\?]/g,Wb=/[#\?@]/g,Vb=/#/g,P=,R=;l=P.prototype;l.add=;l.remove=;l.clear=;l.R=;l.forEach=;
l.B=;l.v=;l.set=;
l.get=;l.toString=;l.clone=;
var S=;P.prototype.ma=;P.prototype.extend=;var Yb=db();function Zb(a){return a?a.passive&&Yb()?a:a.capture||!1:a}var $b=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,Zb(d)):a.attachEvent&&a.attachEvent("on"+b,c)},ac=function(a,b,c,d){a.removeEventListener?a.removeEventListener(b,c,Zb(d)):a.detachEvent&&a.detachEvent("on"+b,c)};var bc=;var cc=,dc=;var ec=/^https?:\/\/(\w|-)+\.cdn\.ampproject\.(net|org)(\?|\/|$)/,fc=,gc=;var hc=;var ic=,jc=,lc=,kc=,T=,nc=,mc=;var oc=;var pc=null;var qc=,rc=function(){var a=void 0===a?u:a;return(a=a.performance)&&a.now?a.now():null};var sc=function(a,b,c){this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=this.label+"_"+this.type+"_"+Math.random();this.slotId=void 0};var U=u.performance,tc=!!(U&&U.mark&&U.measure&&U.clearMarks),uc=db(function(){var a;if(a=tc){var b;if(null===pc){pc="";try{a="";try{a=u.top.location.hash}catch(c){a=u.location.hash}a&&(pc=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=pc;a=!!b.indexOf&&0<=b.indexOf("1337")}return a}),wc=function(){var a=vc;this.T=[];this.Ja=a||u;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.T=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.L=uc()||(null!=b?b:
1>Math.random())};wc.prototype.disable=function(){this.L=!1;this.T!=this.Ja.google_js_reporting_queue&&(uc()&&za(this.T,xc),this.T.length=0)};var xc=;wc.prototype.start=function(a,b){if(!this.L)return null;var c=rc()||qc();a=new sc(a,b,c);b="goog_"+a.uniqueId+"_start";U&&uc()&&U.mark(b);return a};
wc.prototype.end=function(a){if(this.L&&w(a.value)){var b=rc()||qc();a.duration=b-a.value;b="goog_"+a.uniqueId+"_end";U&&uc()&&U.mark(b);this.L&&this.T.push(a)}};var Ac=function(){var a=yc;this.va=zc;this.Ha="jserror";this.ya=!0;this.oa=null;this.Ga=this.ta;this.ca=void 0===a?null:a;this.Ba=!1},Cc=function(a,b){try{if(a.ca&&a.ca.L){var c=a.ca.start((374).toString(),3);var d=b();a.ca.end(c)}else d=b()}catch(f){b=a.ya;try{xc(c);var e=Bc(f);b=a.Ga.call(a,374,e,void 0,void 0)}catch(g){a.ta(217,g)}if(!b)throw f;}return d},Ec=function(a){var b=Dc;return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];return Cc(b,function(){return a.apply(void 0,
d)})}};
Ac.prototype.ta=;
var Bc=,Fc=,Gc=;
na(Gc,bc);
var V=,Ic=function(a,b,c,d,e){c=void 0===c?null:c;d=void 0===d?null:d;e=void 0===e?null:e;"0.01"<Math.random()||(a=Q(Q(Q(Q(Q(new N("//pagead2.googlesyndication.com/pagead/gen_204"),"id","sodarir"),"v",30),"d",a?1:0),"s",b?1:0),"f","0.01"),d&&Q(a,"li",d),e&&Q(a,"cv",e),c&&Q(a,"bgai",c),hc(window,a.toString()))},Lc=function(){void 0===Jc&&(Jc=Kc())},Jc,Mc=function(){new Lc;return Jc||null},
Kc=function(){var a=window.GoogleTyFxhY;if(!a)return V(13),null;if(0==a.length)return V(1),null;a=a.shift();return(a._scs_||a._cv_)&&a._bgu_&&a._bgp_?a:(V(2),null)},Oc=function(a,b){return function(){try{return a.apply(this,arguments)}catch(f){if(!(1<=Nc.count)){var c=f,d=Hc(3),e=Mc()._scs_;e&&Q(d,"bgai",e);Q(d,"c",b);Q(d,"ex",Fc(c));c=d.toString();2E3<c.length?V(11,e):hc(window,c);Nc.count+=1}}}},Nc={count:0},Pc=function(a,b){b=Oc(b,"i:lh");$b(a,"load",b,{capture:void 0});return b},Qc=function(a,
b){var c=b;var d=Pc(a,function(){if(c){var b=c;c=null;ac(a,"load",d,{capture:void 0});return b.apply(this,arguments)}})},Rc=function(){return Ca()};;var Tc=;var Uc=;na(Uc,K);Uc.prototype.next=;var Vc={};var Wc=;var Xc=!F||9<=Number(Za),Yc=!F||9<=Number(Za),Zc;
if(Zc=F){var $c;if(Object.prototype.hasOwnProperty.call(Ya,"9"))$c=Ya["9"];else{for(var ad=0,bd=Fa(String(Xa)).split("."),cd=Fa("9").split("."),dd=Math.max(bd.length,cd.length),ed=0;0==ad&&ed<dd;ed++){var fd=bd[ed]||"",gd=cd[ed]||"";do{var W=/(\d*)(\D*)(.*)/.exec(fd)||["","","",""],X=/(\d*)(\D*)(.*)/.exec(gd)||["","","",""];if(0==W[0].length&&0==X[0].length)break;ad=Ga(0==W[1].length?0:parseInt(W[1],10),0==X[1].length?0:parseInt(X[1],10))||Ga(0==W[2].length,0==X[2].length)||Ga(W[2],X[2]);fd=W[3];
gd=X[3]}while(0==ad)}$c=Ya["9"]=0<=ad}Zc=!$c}var hd=Zc,id=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});u.addEventListener("test",x,b);u.removeEventListener("test",x,b);return a}();var jd=;jd.prototype.stopPropagation=;jd.prototype.preventDefault=;var Y=;wa(Y,jd);
var ld=[1,4,2],kd={2:"touch",3:"pen",4:"mouse"},md=;Y.prototype.stopPropagation=;Y.prototype.preventDefault=;var nd="closure_listenable_"+(1E6*Math.random()|0),od=0;var pd=,qd=;var rd=;rd.prototype.add=;rd.prototype.remove=;
rd.prototype.hasListener=;var td=;var ud="closure_lm_"+(1E6*Math.random()|0),vd={},wd=0,yd=,Ad=,Cd=,xd=,Dd=,Gd=,Fd=,Ed=,Bd=,Hd="__closure_events_fn_"+(1E9*Math.random()>>>0),zd=;var Id=function(a){var b=a._scs_,c=a._li_,d=Rc();if(d&&d.getBoundingClientRect){var e=0;yd(d,"mouseover",);yd(d,"mousedown",)}};var Jd=document,Kd=window;var Ld=!!window.google_async_iframe_id,Z=Ld&&window.parent||window;var zc,Dc;if(Ld&&!cc(Z)){var Md="."+Jd.domain;try{for(;2<Md.split(".").length&&!cc(Z);)Jd.domain=Md=Md.substr(Md.indexOf(".")+1),Z=window.parent}catch(a){}cc(Z)||(Z=window)}var vc=Z,yc=new wc;zc=new function(){var a=void 0===a?Kd:a;this.Pa="http:"===a.location.protocol?"http:":"https:";this.l="pagead2.googlesyndication.com";this.j="/pagead/gen_204?id=";this.Fa=.01;this.Ra=Math.random()};Dc=new Ac;
"complete"==vc.document.readyState?vc.google_measure_js_timing||yc.disable():yc.L&&$b(vc,"load",function(){vc.google_measure_js_timing||yc.disable()});var Nd=function(){var a,b,c=new H(function(c,e){a=c;b=e});return new Db(c,a,b)}();function Od(a){a:{try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?c.parentWindow||c.defaultView:window}else d=null;b=d}var e=b;break a}catch(f){}e=null}Nd.resolve([(0==a.src.indexOf("https:")?"https":"http")+"://tpc.googlesyndication.com",e])}
function Pd(){var a=document.createElement("IFRAME".toString());Qc(a,ua(Od,null,a));a.src="//tpc.googlesyndication.com/sodar/Enqz_20U.html";a.width="0";a.height="0";a.style.display="none";document.body.appendChild(a)}
function Qd(){Nd.Oa.then(function(a){var b=q(a);a=b.next().value;b=b.next().value;var c=Mc();var d=c._scs_;var e=c._bgu_,f=c._bgp_,g=c._li_;c=c._cv_;var h=document.location.origin,k={};d=(k["0"]="0",k["1"]=d||"",k["2"]=e.split("/").pop().replace(/\.js/g,""),k["3"]=f,k["4"]=g||"",k["5"]=c||"",k["8"]=h&&"null"!=h?h:"*",k);b?b.postMessage(d,a):V(3)})};(function(a,b,c){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];Oc(a,b).apply(null,d instanceof Array?d:oa(q(d)))})(function(){var a=!!window.postMessage,b=!1,c=null,d=null,e=null,f=Mc();f&&(b=!0,c=f._scs_,d=f._li_,e=f._cv_,a?(Pd(),Qd()):V(8,c,d,e),setTimeout(Ec(function(){return Id(f)}),0));Ic(b,a,c,d,e)},"i:i");}).call(this);
